Updated GoBuster Guide
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #1010
Opened 2024-11-21 02:49 UTC by TanvirRahmanTaiyeb

2024-11-21 03:17 UTC, cjboyd1999 requested changes
Changes look fine, my suggestion is to add the following:

- Regarding step 2, where can a wordlist file be found? Add an example such as `/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt`
- Add a final step, step 3, to simply say "Click Start GoBuster"

2024-11-22 07:38 UTC, TanvirRahmanTaiyeb commented
Hi Cam, I have made the necessary changes as per your feedback. Can you please check and approve it?

2024-11-23 23:44 UTC, cjboyd1999 requested changes
Once you've made the changes as noted in my previous comment, please re-commit and I will review again.

2024-11-23 23:44 UTC, cjboyd1999 commented on src/components/GobusterTool/Gobuster.tsx
> +`;
The changes you've made should not be in the `const description_userguide` field, please revert this back to what it is in the current `main` branch.

Changes to the steps that are displayed when actually using the tool should be edited in the `const description` field in the `const GoBusterTool = () => {` class. Please see the existing steps on line 49 of your current `Gobuster.tsx` edit.

At the moment, your edits are not reflected in the UI.

2024-11-26 00:35 UTC, closed without merging