baseline bug fix
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #1033
Opened 2024-11-25 09:57 UTC by Arsh1303

• Removed the unused inputs from the code
• Added the appropriate docstring to the functions and interface
• Changed the state variables to camelCase
• Added inline comments to all react hooks
• Added inline comments to all component constant
• Changed the tool title with respect to the documentation
• Added the steps in component description
• Add useEffect for checking command availability
• Added sourceLink and updated it with the appropriate link
• Added empty string in tutorial
• Fixed grammar issues
• Added comments and docstrings in functions
• Added the function handleSaveComplete with appropriate comments and docstring
• Added the render component which was not there in the code
• Changed the file saving to output_V2
• Committed the code and generated a pull request

2024-12-03 02:48 UTC, cjboyd1999 requested changes
Please make the changes as requested below.

Once you have done that, please **ensure you are testing your changes before submitting a PR**. If you find anymore issues while testing yourself, please fix them before submitting, otherwise it just eats up my time during testing.

2024-12-03 02:48 UTC, cjboyd1999 commented on src/components/msfvenom/msfvenom.tsx
> +        "android/shell/reverseTcp",
All of these changes will need to be undone. These are the arguments passed to `msfvenom` to determine what type of payload should be used.

As an example, if you try to run `msfvenom` with the payload (`-p`) "`windows/meterpreter/reverseTcp`", the command will fail as the payload is invalid. The snake-case used here is what `msfvenom` uses to denote it's payloads, so please change them back.

2025-01-06 01:24 UTC, sreedharashwin commented
The above requested changes are yet to be made, could you please revisit your code and make changes as per the review? Thanks.

2025-03-16 13:38 UTC, closed without merging

2025-03-16 13:38 UTC, GoldenBanksia commented
Changes not implemented, and author no longer contributing to project. Closed PR as unable to be resolved.