Fixed tool functionaility + implemented SaveOutputToTextFile_v2
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #432
Opened 2023-11-26 05:10 UTC by v-xl

In the Tauri config, for the gobuster command, the ‘G’ was capitalised which is the cause of the issue, since the command itself should be executed in all lower case. This has been modified and tested successfully.

A bug I found with this tool, the existing Output file textbox didn't do anything, and no Output file was created upon running the tool. 

I've modified the code to remove the existing Output textbox, and I've instead implemented the SaveOutputToTextFile_v2 function as per the documentation in Teams. After modifying the code and implementing the SaveOutputToTextFile_v2 function all is working as intended and the output file will be created.

2023-11-27 01:25 UTC, Sakada-lim approved these changes
Overall the code is good but more feature should be added for gobuster. 
### idea for improvement

1. Add more feature for gobuster
2. implement the `-o` feature alongside the `{Saveoutputtofile_v2}`
3. make the onsubmit more scalable

2023-11-27 01:25 UTC, Sakada-lim commented on src/components/GobusterTool/Gobuster.tsx
> +                {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
This is not a bug. `-o` is a feature that allow the user to save the output result to a file name. However, with that being said, it is very similar to `{SaveOutputTotextFile_v2}`. The difference is `{SaveOutputTotextFile_v2}` save the whole command include all the print value during the execution but `-o` only print the result.

2023-12-02 23:29 UTC, gangamarx commented
gobuster works well in CLI mode but do not work at all in GUI. Please looks at the screen shots
![gobuster works in CLI mode](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/b78d0b20-8080-4905-8620-8ae6f033fba8)
![gobuster dont work in gui for any URL](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/5e9d32a8-b48f-47e0-9eb6-2732cf6e88e3)

2023-12-02 23:30 UTC, gangamarx requested changes
gobuster works in CLI mode but not in GUI mode.
![gobuster works in CLI mode](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/ca5ddf45-4f94-4d8a-bf30-0e420777d8d2)
![gobuster dont work in gui for any URL](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/46d42e76-6fba-404a-8c2c-dbfe28627d70)

2023-12-03 01:43 UTC, v-xl commented
Thank you, this was due to the Tauri config. It looks like I've forgotten to commit the updated file.
I've now fixed this.

2023-12-06 07:44 UTC, gangamarx commented
I will mark this task as complete.

2023-12-13 02:36 UTC, Phaellynn approved these changes
GoBuster has passed all functionality tests as reviewed by Ganga Marx
Tool now scans as expected without errors.
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/57789037/48e35bb3-f498-4088-b606-f42de951236e)

2023-12-13 02:47 UTC, gangamarx approved these changes
The tool now works as expected without any errors.

2023-12-13 11:30 UTC, merged