Fcrackzip
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #451
Opened 2023-12-09 04:57 UTC by YashKanodia

Fcrackzip - The below issue is fixed 

When 'Show Cracked Password' is selected user can no longer select a character set (the Lowercase/Uppercase/Numeric) boxes become inactive. 

<img width="953" alt="gmail" src="https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/48887120/06febb0d-16e4-4c15-b071-291f4267af06">

Here, in the screenshot I have checked "Use UpperCase" and "Use Numeric" and when checked "Show Cracked Password" the boxes are still active.

2023-12-09 07:09 UTC, Phaellynn submitted a review, later dismissed
This issue is only HALF fixed. So issue is not fixed.
- When selecting the Charset List BEFORE selecting the 'Show cracked password' checkbox, the selection remains active, but still 'greyed out' and you cannot update the Charset List.
- You cannot select the Charset List AFTER selecting the 'Show cracked password' checkbox.
![Screenshot 2023-12-09 180735](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/57789037/52efa39c-a248-4aec-bb15-e1dc17066b38)

- The same issue is not present when selecting the 'Verbose mode' checkbox.
![Screenshot 2023-12-09 180702](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/57789037/f69597e7-a2bd-4dfb-b994-eaca0b50fe40)

- There also appears to be an extra issue that wasn't present before. There are now TWO 'Clear Output' buttons instead of just the one. Please remove one of them.
![Screenshot 2023-12-09 181057](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/57789037/4eb7f16b-2617-4954-8fb8-a4a86b6b78a7)

2023-12-10 06:17 UTC, YashKanodia commented
As discussed with Liz, there's a pending discussion with Sakada and Bradley on the above issues.

2023-12-14 10:39 UTC, bradleybogg requested changes

2023-12-16 04:23 UTC, Sakada-lim approved these changes
Adjusted and tested by Admin

2023-12-16 04:23 UTC, Sakada-lim commented on src/components/Fcrackzip/Fcrackzip.tsx
admin have personally adjust this pull request and make some change in order to make the code work

2023-12-16 04:24 UTC, merged