Zerologon attack vector added
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #48
Opened 2022-09-05 03:33 UTC by falshamri

2022-09-05 04:36 UTC, PurpleSn0w commented on src-tauri/exploits/secretsdump.py
> +#
A Reference entry need to be added to the references page. (However still leave these code comments here.)
For guidance follow whats required from the tool you have implemented: https://apache.org/licenses/LICENSE-2.0
Make sure to link that page in the reference entry. As required in section 4.a of the agreement

2022-09-05 05:54 UTC, Huskehhh requested changes
Minor changes / comments - but looks really good!

2022-09-05 05:54 UTC, Huskehhh commented on src/components/ZeroLogon/Zerologon.tsx
> +    const [selectedVersion, setSelectedVersion] = useState("2.4.49");
can remove this

2022-09-05 05:54 UTC, Huskehhh commented on src-tauri/exploits/secretsdump.py
> +#!/usr/bin/env python
hmmm. can we perhaps add impacket as a submodule or and clone it in our install dependencies script

2022-09-06 00:20 UTC, Huskehhh commented on src-tauri/exploits/secretsdump.py
> +#!/usr/bin/env python
apparently this now comes with kali

2022-09-06 00:21 UTC, Huskehhh commented on src/components/ZeroLogon/Zerologon.tsx
> +    const [selectedVersion, setSelectedVersion] = useState("2.4.49");
aa53fbc

2022-09-06 00:25 UTC, Huskehhh commented on src-tauri/exploits/secretsdump.py
> +#!/usr/bin/env python
made it a dep via 0177fdb

2022-09-06 00:29 UTC, Huskehhh commented on src-tauri/exploits/secretsdump.py
> +#!/usr/bin/env python
Done 8453cfe

2022-09-06 00:30 UTC, Huskehhh commented on src-tauri/exploits/secretsdump.py
> +#
Will leave this for you - @falshamri

2022-09-07 08:45 UTC, PurpleSn0w approved these changes
Well done, Thanks

2022-09-13 02:43 UTC, Huskehhh approved these changes

2022-09-13 02:43 UTC, merged