Wpscan Bug Fix
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #495
Opened 2024-03-19 09:30 UTC by zkkok

# Changes 

- **Reduced Code Redundancy:** Replaced some unnecessary checkboxes with NativeSelect and TextInput
- **Custom Mode:** Removed some uncommon features and added a custom configuration option to make the GUI look less packed
- **Tooltip and Placeholder Descriptions:** Corrected the grammatical error in the tooltip and added some placeholder descriptions to  better describe each option

Link issue to #415

2024-04-08 10:14 UTC, bradleybogg commented
@zkkok - I found this useful https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/
I have learnt some information here too that would be beneficial in future commits. I will look to implement in my work also.

2024-04-10 08:29 UTC, gangamarx commented
During my initial review, I came across some error messages in the output, although the tooltips seemed fine. Therefore, I'm updating the DDT to make sure it's free of errors.

2024-04-10 08:45 UTC, zkkok commented
@gangamarx could you please provide more details about the error u encountered?

2024-04-10 09:29 UTC, gangamarx commented
WPScan test version: 5deef3c - Bradley Bogg, 2 days ago : Merge pull request #524
1. Tooltip reads well and error free. I made a suggestion though!. See attached file
2. I scanned the URL https://sites.lsa.umich.edu/julian/ and the test results are great-successful. See attached a file
3. In the advanced mode there is spelling error "Login URL". See attached file
[1-Suggestion for Tooltip.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/14930352/1-Suggestion.for.Tooltip.docx)
![2-WPScan output review](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/484c3a11-0f47-4ea2-9117-59b0b22ba335)
![3-Advanced Mode spelling mistake-login URL](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/dd8d5d3e-9768-4251-abdc-ff7bf115ab64)

2024-04-10 09:31 UTC, gangamarx commented
I didn't take a screen shot as I found the head was different, now I fixed that. Results are great. Should I be checking the advanced mode too ?

________________________________
From: zkkok ***@***.***>
Sent: Wednesday, 10 April 2024 6:45 PM
To: Hardhat-Enterprises/Deakin-Detonator-Toolkit ***@***.***>
Cc: GANGA MARX ***@***.***>; Mention ***@***.***>
Subject: Re: [Hardhat-Enterprises/Deakin-Detonator-Toolkit] Wpscan Bug Fix (PR #495)


@gangamarx<https://github.com/gangamarx> could you please provide more details about the error u encountered?

—
Reply to this email directly, view it on GitHub<https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/495#issuecomment-2046927578>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQLVUBOTANY5B2ZVVVNEZ33Y4T32FAVCNFSM6AAAAABE5FJZPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBWHEZDONJXHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-04-13 00:31 UTC, bradleybogg commented
@gangamarx, test the entire tool and compare against what is requested in the card. All PRs are linked to an issue which describes what should have been changed.

2024-04-15 07:07 UTC, gangamarx commented
Apologies for the delay; I was thoroughly reviewing the results from the advanced options. I've included a summary in document format and added screenshots for clarity. While most commands functioned correctly in CLI mode, only 3 out of 41 worked in GUI mode. I conducted the tests to the best of my abilities with the knowledge I have and am submitting this review accordingly.
[WPscan Advanced mode -test results.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/14975327/WPscan.Advanced.mode.-test.results.docx)

2024-04-15 07:08 UTC, gangamarx reviewed
Apologies for the delay; I was thoroughly reviewing the results from the advanced options. I've included a summary in document format and added screenshots for clarity. While most commands functioned correctly in CLI mode, only 3 out of 41 worked in GUI mode. I conducted the tests to the best of my abilities with the knowledge I have and am submitting this review accordingly.
[WPscan Advanced mode -test results.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/14975338/WPscan.Advanced.mode.-test.results.docx)

2024-04-16 01:02 UTC, zkkok commented
Hi @gangamarx,

Thanks for carrying out the functionality tests. However, based on the document you provided it seems that you are performing the tests on the old version of the tool, please switch to the WPSScan-Fix branch and perform the tests based on the updated code.

2024-04-16 01:20 UTC, gangamarx commented
Thanks @zkkok , I apologize wasting time working on the incorrect branch. I will work on the right one now and send the results asap. Cheers

2024-04-17 04:10 UTC, bradleybogg commented
@gangamarx please conduct application testing.

2024-04-18 02:45 UTC, gangamarx commented
Conducted the application testing on new WPSscan-Fix branch. All tests were successful. Attached is the evidence of test.
[WPSScan-Fix-Advanced testing review.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15019286/WPSScan-Fix-Advanced.testing.review.docx)

2024-04-18 05:03 UTC, gangamarx reviewed
Conducted the application testing on new WPSscan-Fix branch. All tests were successful. Attached is the evidence of test.
[WPSScan-Fix-Advanced testing review.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15019286/WPSScan-Fix-Advanced.testing.review.docx)

2024-04-18 05:04 UTC, gangamarx commented
No grammatical errors in the tool tip. All looks okay.

2024-04-20 13:34 UTC, bradleybogg requested changes
Wow good work simplifying this component was previously very poorly written.
Can you please update the variable naming please.

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +const enumerationtypesrequiringupdownbound = ["UID range", "MID range"];
- [ ] Camelcase required
- [ ] Simplify variable naming

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +const detectionmodes = ["mixed", "passive", "aggressive"];
- [ ] camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +const outputformats = ["cli-no-colour", "cli-no-color", "json", "cli"];
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    lowbound: number;
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    upbound: number;
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    customenum: string;
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    const [selectedenumerationtype, setselectedenumerationtype] = useState("");
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    const [checkedCustom, setcheckedCustom] = useState(false);
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    const [selecteddetectionmode, setselecteddetectionmode] = useState("");
- [ ]  camelCase

2024-04-20 13:34 UTC, bradleybogg commented on src/components/WPScan/WPScan.tsx
> +    const [selectedoutputformat, setselectedoutputformat] = useState("");
- [ ]  camelCase

2024-04-20 14:38 UTC, bradleybogg approved these changes

2024-04-20 14:38 UTC, merged