Updated path in affected components.
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #515
Opened 2024-03-30 06:21 UTC by slpysiren

Updated paths to exploits to reflect the intended exploit path.

2024-03-30 22:25 UTC, bradleybogg reviewed
@slpysiren Please validate that each component's external reference originally is found within the exploits dir.

Need to ensure that post installation they are copied.

Please comment once verified and I'll start testing.

- [x] Verify each tool will be moved once installed.

2024-03-30 23:56 UTC, bradleybogg reviewed
Changes look good awaiting confirmation.

2024-03-31 06:59 UTC, zkkok requested changes

2024-03-31 06:59 UTC, zkkok commented on src/components/Ffuf/FfufTool.tsx
> +    "Wordlist directory: /usr/shar/ddt/ffuf_wordlists/\n\n" +
Seems to be a spelling error. Should be share instead of "shar"

2024-03-31 07:57 UTC, slpysiren commented on src/components/Ffuf/FfufTool.tsx
> +    "Wordlist directory: /usr/shar/ddt/ffuf_wordlists/\n\n" +
Thanks for catching this! Fixed now.

2024-03-31 08:19 UTC, slpysiren commented
> @slpysiren Please validate that each component's external reference originally is found within the exploits dir.
> 
> Need to ensure that post installation they are copied.
> 
> Please comment once verified and I'll start testing.
> 
>     * [ ]  Verify each tool will be moved once installed.

I have verified all but one, GoldenEye doesn't seem to be included in its folder. I have found the tool on GitHub and attempted to include its files however, the GoldenEye folder seems to be listed as a submodule and I'm unable to stage any file additions inside. I can confirm the path would be correct if or when this is fixed.

2024-04-08 11:18 UTC, bradleybogg approved these changes

2024-04-08 12:05 UTC, zkkok approved these changes
Well done, no issues with the changes

2024-04-10 10:01 UTC, slpysiren commented
> Hi @slpysiren,
> 
> When creating your branch please use the convention we have specified. This is best completed by creating it from the github issue.
> 
> Kind Regards,
> 
> Bradley

Hi Bradley, 

I'm not certain how to verify this but I believe I didn't create the branch. Though I will be sure to keep this in mind in future.

Thanks.

2024-04-10 10:51 UTC, merged