Advance mode for AirebaseNG added
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #531
Opened 2024-04-09 06:16 UTC by AnkitB125

Added the advance mode option for the airebaseNG by adding wep key argument to encrypt or decrypt the packets

2024-04-09 19:01 UTC, zkkok commented
Hi @AnkitB125 ,

Thanks for your contribution. 

Please note that we use the trello board as the main way of assigning tasks. In the future, please go through the trello board to assign yourself the task you want to be working on and communicate with your peers currently working on it before commencing. This is to avoid collision.

Also, please generate the branch from the original issue.

2024-04-10 10:54 UTC, bradleybogg commented on src/components/AirbaseNG/AirbaseNG.tsx
Changes look good. Pending @gangamarx application testing.

2024-04-18 07:30 UTC, gangamarx commented on src/components/AirbaseNG/AirbaseNG.tsx
@AnkitB125 airbase-advance-mode
I am seemed to get an error when I did the testing both in standard mode and advanced mode in my laptop. Upon researching the error message, it says the SSID or WLAN meant to be in quotes as there is a space in WLAN etc. Please advice if I need to setup anything correctly. Attached is the error msg screenshot. 
[Standard test error.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15021358/Standard.test.error.docx)

2024-04-18 07:30 UTC, gangamarx reviewed
@AnkitB125 airbase-advance-mode
I am seemed to get an error when I did the testing both in standard mode and advanced mode in my laptop. Upon researching the error message, it says the SSID or WLAN meant to be in quotes as there is a space in WLAN etc. Please advice if I need to setup anything correctly. Attached is the error msg screenshot. 
[Standard test error.docx](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15021358/Standard.test.error.docx)

2024-04-28 06:48 UTC, bradleybogg requested changes
Please rectify the above requested changes.

2024-05-06 12:20 UTC, AnkitB125 commented
I did not tested the airbaseNG on my system since I am using Window and I followed the following guide to implement the advance mode
[MN503_Assignment_2_T1_2024.pdf](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15220472/MN503_Assignment_2_T1_2024.pdf)

2024-05-08 01:13 UTC, michaeljpigott commented
Hi @AnkitB125, can you please resolve the conflicts with this branch? Click on _Resolve conflicts_ for more information. You also need to figure out the issue raised by Ganga.

2024-08-18 23:28 UTC, michaeljpigott commented
This pull request is out-of-date (from Trimester 1, 2024).

2024-08-18 23:28 UTC, closed without merging