297 saveoutputtotextfile ddt wide rollout
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #536
Opened 2024-04-10 02:40 UTC by CAfitech

We have updated the code of all tools and attack vectors to incorporate saveoutputtotectfil_v2.

2024-04-10 10:16 UTC, zkkok requested changes
Hi @hhenryDeakin @CAfitech,
Appreciate the great work both of you have produced. However, it looks like your code have generated some conflicts. This might be due to some commits you have done one some of the yarn files. The rule of thumb for committing the files is to only commit those you have been working in. Files like yarnrc.yml, yarn.lock are automated processes that does not need to be committed.

Additionally here's a guide on writing better commit messages and pull requests:
https://www.freecodecamp.org/news/how-to-write-a-pull-request-description/
https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/

2024-04-10 10:16 UTC, zkkok commented on .yarn/install-state.gz
Please do not commit this file

2024-04-10 10:16 UTC, zkkok commented on .yarnrc.yml
Please do not commit this file

2024-04-10 10:16 UTC, zkkok commented on yarn.lock
Please do not commit this file

2024-04-12 02:23 UTC, CAfitech commented on yarn.lock
Thanks, I have made the adequate changes.

2024-04-12 02:23 UTC, CAfitech commented on .yarnrc.yml
Thanks, I have made the adequate changes.

2024-04-12 02:23 UTC, CAfitech commented on .yarn/install-state.gz
Thanks, I have made the adequate changes.

2024-04-12 09:36 UTC, zkkok commented on yarn.lock
Hi @CAfitech, you have not removed the yarn.lock file

2024-04-13 00:37 UTC, closed without merging

2024-04-13 00:37 UTC, bradleybogg commented
Hi Team, please make the requested changes. When ready then create the PR. Thank you!