532 bug enum4linux tooltip grammar
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #557
Opened 2024-04-15 11:13 UTC by anjojoseph

Hi,
532 bug enum4linux tooltip grammar task is completed. 
Kindly check and merge the branch.
Thank you.

2024-04-16 01:05 UTC, bradleybogg requested changes

2024-04-16 01:05 UTC, bradleybogg commented on src/components/Enum4Linux/Enum4Linux.tsx
Hi @anjojoseph,

These changes are very good and do not technically need further editing. I will ask for some changes though just to bring in line with other tool tips.

Very good work. After the below changes please look for a task with a 'medium' difficulty. This is to ensure you start making evidence for at least a passing grade.

2024-04-16 01:05 UTC, bradleybogg commented on src/components/Enum4Linux/Enum4Linux.tsx
>      "       Eg: 192.168.1.1\n\n" +
Make in line with line 17. Remove \n\n after the example and simply have it read:

Step 1: Enter a target IP address. E.g 192.168.1.1\n" +

2024-04-16 01:05 UTC, bradleybogg commented on src/components/Enum4Linux/Enum4Linux.tsx
>      "       Eg: U (get userlist)\n\n" +
Make in line with line 19. Remove \n\n after the example and have it simply read:

"Step 2: Enter an option for the enumeration. E.g U (get userlist)\n" +

2024-04-16 01:05 UTC, bradleybogg commented on src/components/Enum4Linux/Enum4Linux.tsx
>      "       Eg: example.txt\n\n" +
Make in line with line 21. Remove \n\n after the example and have it simply read:

"Step 3: Enter any parameters. E.g example.txt. \n" +

2024-04-28 06:53 UTC, bradleybogg commented
Requested changes not implemented. Please re-raise when completed.

2024-04-28 06:53 UTC, closed without merging

2024-04-29 00:38 UTC, anjojoseph commented
Changes has been done. opened pull request : 532 bug enum4linux tooltip grammar #639