Feature request- Bully tool
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #562
Opened 2024-04-16 06:00 UTC by chandelshubham63

Implemented the Bully tool in DDT. This tool is used for brute-forcing WPS PIN authentication and can be used to test the security of Wi-Fi networks. The tool allows the user to specify the access point interface or SSID, along with a password list and an optional BSSID. The tool then attempts to brute-force the WPS PIN using the provided settings and outputs the results to the console.

Changes:
Added a new component for the Bully tool in src/components/Bully.tsx
Added the Bully tool to the ROUTES array in src/components/RouteWrapper.tsx
Added the Bully tool to the tauri.conf.json file to allow it to be executed as a command.

Tested the tool with various settings and confirmed that it is working as expected.
To test the tool, simply navigate to the Bully tool in DDT and provide the necessary settings. The tool will then attempt to brute-force the WPS PIN and output the results to the console.

2024-04-17 05:12 UTC, bradleybogg requested changes
Good Work!

please see requested changes before proceeding to application review.

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    Interface: string;
- [ ] camelCase

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    PasswordList: string;
- [ ] camelCase

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    BSSID: string;
- [ ] camelCase

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    ESSID: string;
- [ ] camelCase

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +const Bully = () => {
- [ ] Comment to denote state variables.

Check Aircrack for review.

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    const onSubmit = async (values: FormValuesType) => {
- [ ] In line comments missing.

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +            const commandOutput = await CommandHelper.runCommand("bully", args);
- [ ] Need to use getpidandoutput this is deprecated command

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +            const commandOutput = await CommandHelper.runCommand("bully", args);
Need to use canceloverlay

2024-04-17 05:12 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +            <LoadingOverlay visible={loading} />
- [ ] Need to implement the checkinstalled

See Aircrack for example.

2024-04-28 07:05 UTC, bradleybogg requested changes
Overall @chandelshubham63 

Very good work. I appreciate that you have implemented the newer versions of the codebase. There is some more work to be done to ensure that this component is also 'baselined'.

Cheers

2024-04-28 07:05 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +    const handleSaveComplete = () => {
- [ ] Upgrade to docstring.

2024-04-28 07:05 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +                        Start Bully Attack
<Button type={"submit"}>Start {title}</Button>

- [ ] Use now known variables.

2024-04-28 07:05 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +                    {UserGuide(title, description_userguide)}
- [ ] camelCase

2024-04-28 07:05 UTC, bradleybogg commented on src/components/Bully/Bully.tsx
> +                    feature_description={description_userguide}
- [ ] camelCase

2024-05-04 10:46 UTC, bradleybogg commented
@chandelshubham63 

I have rectified your errors because you did not push the libraries you were using from main into your branch.
I cannot complete this application testing without the wireless adapter. Please upload evidence of the tool working as expected.

Thank you!

2024-05-04 10:47 UTC, bradleybogg reviewed
Please upload as requested.

2024-05-09 08:02 UTC, zkkok commented
Hi @chandelshubham63 ,
Please resolve the conflicts before application testing

2024-05-10 04:05 UTC, zkkok requested changes
Hi @chandelshubham63,

Please review your code again, the code doesn't run properly. `-i` is not use to specify the interface and `-f` is not an available parameter for the tool please have a look at the kali documentation for the tool.
https://www.kali.org/tools/bully/

2024-05-10 05:48 UTC, chandelshubham63 commented
Thanks for the feedback @zkkok . I modified the code to follow the requested changes

2024-05-11 09:09 UTC, zkkok commented
@chandelshubham63 ,Application testing has been done.

The tools runs smoothly and provided the expected outputs.

Input:
<img width="415" alt="image" src="https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/114792383/c84f32d0-d88f-4728-b0c0-addbbcbf2a02">

Output:
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/114792383/bf448648-504c-4b6f-966e-058509d99a1a)

2024-05-11 09:09 UTC, zkkok approved these changes

2024-05-12 00:45 UTC, merged