Tooltip Grammatical Error Corrections
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #568
Opened 2024-04-16 09:07 UTC by chyrm

2024-04-17 05:13 UTC, bradleybogg requested changes
@chyrm 

It is not acceptable to have no description.
Please amend this to reflect the changes you have completed. I will then proceed with review.

2024-04-28 07:08 UTC, bradleybogg requested changes
Please see requested changes.

2024-04-28 07:08 UTC, bradleybogg commented on src/components/Urlsnarf/Urlsnarf.tsx
> +    // "Urlsnarf is a network traffic sniffing tool that works to output all URL's that are requested from HTTP " +
- [ ] remove comments that are not required

2024-04-28 07:08 UTC, bradleybogg commented on src/components/Urlsnarf/Urlsnarf.tsx
@chyrm 

Please also remember to only change the elements that are within the specified issue. This is good practice to ensure that small changes dont hold up your entire PR.

In this case you have extended changes to more than the tooltip. This is relevant because the PR now requires application testing and additionally does not confirm with the baseline activities that are being undertaken.

Thank you!

2024-05-01 03:59 UTC, gangamarx commented
Hi @chyrm 
No grammatical error found in the "545-bug-urlsnarf-tooltip"
But when ran the tool in GUI you get the following error:
"urlsnarf: eth0: You don't have permission to perform this capture on that device (socket: Operation not permitted)"
It worked with sudo command in CLI ok. "" sudo urlsnarf -i eth1 -v"
![Error in GUI](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/22a4e18a-2469-4a6f-a518-56b0e6544cc2)
![no error in CLI with sudo](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/68639237/d8abd5a7-168a-4044-9521-065d30e8c647)

2024-05-08 05:55 UTC, michaeljpigott commented
Hi @chyrm. Please disregard my previous comment as I forgot that this issue is just about fixing the tooltip. I will have a final check and look to approve your changes. 

Thanks.

2024-05-08 08:41 UTC, michaeljpigott requested changes
Hi @chyrm 

Please correct the grammatical error (changing URL's to URLs) and remove the non-required comment (as advised by Bradley). 

Kind regards

Michael

2024-05-08 08:41 UTC, michaeljpigott commented on src/components/Urlsnarf/Urlsnarf.tsx
> -    "Urlsnarf is a network traffic sniffing tool that works to output all URL's that are requested from HTTP " +
Please change "URL's" to "URLs" because it is plural not possessive. 

- [ ] Update grammatical error

2024-05-10 01:42 UTC, michaeljpigott approved these changes
Thank you @chyrm for making that change. I approve the merge into main. 

Kind regards

Michael

2024-05-10 01:44 UTC, merged