Grammatical errors rectified
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #569
Opened 2024-04-16 09:25 UTC by mariarose-francis

2024-04-17 05:13 UTC, bradleybogg requested changes
@mariarose-francis 

It is not acceptable to have no description.
Please amend this to reflect the changes you have completed. I will then proceed with review.

2024-04-28 07:09 UTC, bradleybogg submitted a review, later dismissed
@mariarose-francis 

Please make sure you push your changes. I cannot see any changes as of yet. 

Thank you!

2024-04-28 07:13 UTC, bradleybogg requested changes
Hi @mariarose-francis,

Thanks for your work.

I have requested some small changes so that you can see this process. The changes here still require some work to be finalized. The purpose of tooltips is to allow you to learn the process of committing and the company.

For this reason, after the changes I intend to approve and have the technical components completed under baselining. 

Thank you!

I recommend that you investigate the baseline task for this component on completion.

2024-04-28 07:13 UTC, bradleybogg commented on src/components/Dnsrecon/Dnsrecon.tsx
> +    "Step 1: Enter a Target Domain URL, for example, https://www.deakin.edu.au\n\n" +
- [ ] please correct the capitalization of the words that is incorrect.

2024-04-28 07:13 UTC, bradleybogg commented on src/components/Dnsrecon/Dnsrecon.tsx
> +    "Step 2: Click Scan to commence DNSRecon's operation.\n\n" +
- [ ] please correct the capitalization of the words that is incorrect.

2024-04-28 07:13 UTC, bradleybogg commented on src/components/Dnsrecon/Dnsrecon.tsx
> +    "Step 3: View the Output block below to view the results of the tool's execution.";
- [ ] please correct the capitalization of the words that is incorrect.

2024-05-01 10:36 UTC, mariarose-francis commented
Closing this PR as I have created a new PR with changes committed.

2024-05-01 10:36 UTC, closed without merging