CVE-2022-36804 Bitbucket server exploitation.
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #615
Opened 2024-04-16 16:10 UTC by blackdot88

Tested on Bitbucket server 7.17.1: https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-7.17.1.zip

2024-04-17 05:17 UTC, bradleybogg requested changes

2024-04-17 05:17 UTC, bradleybogg commented on src-tauri/exploits/cve-2022-36804.py
Requires application testing. @blackdot88 please work with @gangamarx to conduct testing.

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
> +Usage:
Very good!!!

Thank you, such a small difference, but plenty readable. 
Please change use to How to use {toolname}.

This will cahnge in the near future when we do the baseline but for now its good!

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
> +    //const [handle, setHandle] = useState<Child | null>(null);
- [ ] Remove if not required.

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
> +    const [loading, setLoading] = useState(false);
Comment needed

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
> +    const [output, setOutput] = useState<string>("");
Comment needed

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
> +    let form = useForm<FormValues>({
Comment needed

2024-04-17 05:17 UTC, bradleybogg commented on src/components/CVE-2022-36804/CVE-2022-36804.tsx
Will require application testing post review.

2024-04-28 07:14 UTC, bradleybogg commented
@blackdot88 

Please resolve conversations when changes reflect.

2024-04-28 07:14 UTC, bradleybogg commented
@blackdot88 Still pending some changes.

2024-05-13 13:32 UTC, blackdot88 commented on src-tauri/exploits/cve-2022-36804.py
Sent a video ò working exploit via Teams chat. Please review it and confirm.

2024-05-15 00:42 UTC, michaeljpigott commented on src-tauri/exploits/cve-2022-36804.py
Hi @blackdot88, thank you for providing the video. It looks good.

2024-05-15 00:43 UTC, merged