506 feature request arpaname tool
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #624
Opened 2024-04-18 16:12 UTC by Lost-Rain

Adds a new tool called "Arpaname Tool" for translating IP addresses (IPv4 and IPv6) to their corresponding IN-ADDR.ARPA or IP6.ARPA names. This tool includes form validation, command execution, and output display functionalities. Simplified IP validation and separated into IPv4 & IPv6.

2024-04-28 07:45 UTC, bradleybogg requested changes
Hi @Lost-Rain 

This is a good start but it doesnt conform to our baselining standards.
Please review existing components that have completed baselining such as AirBase for reference.

Thank you!

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +import { SaveOutputToTextFile } from "../SaveOutputToFile/SaveOutputToTextFile";
- [ ] Upgrade to V2

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +import { UserGuide } from "../UserGuide/UserGuide";
- [ ] Upgrade to render component

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +const title = "Arpaname Tool";
- [ ] move inside function definition.
- [ ] Remove 'Tool'

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +const description_userguide =
- [ ] move inside function definition.
- [ ] split description and guide into two distinct constants

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    "Arpaname translates IP addresses (IPv4 and IPv6) to the corresponding IN-ADDR.ARPA or IP6.ARPA names.";
- [ ] to their corresponding

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +interface FormValuesType {
- [ ] Add docstrings

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const [errorMessage, setErrorMessage] = useState("");
- [ ] Remove this functionality and append using the callbackfunctions from the helper method.

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    let form = useForm<FormValuesType>({
- [ ] Doc string

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const [loading, setLoading] = useState(false);
- [ ] Add component constant section and comment
- [ ] Add component state variable section and comment

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const handleProcessData = useCallback((data: string) => {
- [ ] doc string
   /**
     * handleProcessData: Callback to handle and append new data from the child process to the output.
     * It updates the state by appending the new data received to the existing output.
     * @param {string} data - The data received from the child process.
     */

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const handleProcessTermination = useCallback(
- [ ] Doc String

    /**
     * handleProcessTermination: Callback to handle the termination of the child process.
     * Once the process termination is handled, it clears the process PID reference and
     * deactivates the loading overlay.
     * @param {object} param - An object containing information about the process termination.
     * @param {number} param.code - The exit code of the terminated process.
     * @param {number} param.signal - The signal code indicating how the process was terminated.
     */

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const validateIPAddress = (ip: string) => {
- [ ] Doc String

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const clearOutput = useCallback(() => {
- [ ] doc string

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +    const onSubmit = async (values: FormValuesType) => {
- [ ] Doc String

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +            setOutput("The input is not a valid IP address. Please try again.");
- [ ] do not call the setOutput outside of its handle function. It is okay in the clear function when we do not want to append

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +        <form onSubmit={form.onSubmit(onSubmit)}>
- [ ] Add Render component
- [ ] Add dependency checker at runtime.

2024-04-28 07:45 UTC, bradleybogg commented on src/components/Arpaname/arpaname.tsx
> +import { LoadingOverlayAndCancelButton } from "../OverlayAndCancelButton/OverlayAndCancelButton";
- [ ] Add dependency checker

2024-05-12 02:12 UTC, michaeljpigott requested changes
Hi @Lost-Rain 

You are getting closer. Please add the SaveOutputToTextFile_v2 functionality to arpaname, use runCommandGetPidAndOuput instead of Pkexec (root privileges are not required), and restore the which command to tauri.conf.json. 

Kind regards

Michael

2024-05-12 02:12 UTC, michaeljpigott commented on src/components/Arpaname/arpaname.tsx
> +                    <ConsoleWrapper output={output} clearOutputCallback={clearOutput} />
This is where the SaveOutputToTextfile_v2 component should be placed.

2024-05-12 02:12 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> +        description: "Perform reverse DNS lookups for IP addresses.",
Please make the description consistent with the description constant in arpaname.tsx.

2024-05-12 02:12 UTC, michaeljpigott commented on src-tauri/tauri.conf.json
> -                        "name": "which",
Why did you remove the which command? Please leave because I am not sure what other tools require that command.

2024-05-15 00:13 UTC, michaeljpigott requested changes
Hi @Lost-Rain 

Thank you for making those changes. 

I am finding that the InstallationModal is popping up even though I have installed Arpaname via Bind9. Not sure how to fix this problem because it is unusual that a dependency does not equate to a command:
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/35479648/e81ccb3c-00d4-4994-83b7-5b52e4909b01)

This might be a fix for future work. If you can add the variables for steps, tutorial and sourcelink in RenderComponent, then we should be done. 

Kind regards

Michael

2024-05-18 03:30 UTC, michaeljpigott approved these changes

2024-05-18 03:31 UTC, merged