branch redone without unwanted files
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #629
Opened 2024-04-22 06:01 UTC by SethJ1

Had to redo a pull request due to certain unwanted files being added, old commits are as follows: 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/102099281/b7b0576a-a118-4910-ae78-b83a99bce3a6)

2024-04-28 07:57 UTC, bradleybogg requested changes
Good Work @SethJ1 

Please see the below changes.

Kind Regards

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +import { UserGuide } from "../UserGuide/UserGuide";
- [ ] Upgrade to render component

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +const title = "Nikto";
- [ ] Move inside function definition.

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +const description_userguide =
- [ ] Seperate into guide and description variables required for render component

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    "How to use this Nikto tool:\n" +
- [ ] Use steps method (Step 1: ...)

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +interface FormValuesType {
- [ ] Doc String required

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    TargetURL: string;
- [ ] camelCase

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    // Initialize state variables
- [ ] Check comment consistency with other components.
// Component State Variables.

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const [loading, setLoading] = useState(false);
- [ ] Inline comment

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const [output, setOutput] = useState("");
- [ ] Inline comment

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const [allowSave, setAllowSave] = useState(false);
- [ ] Inline comment

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const [hasSaved, setHasSaved] = useState(false);
- [ ] Inline comment

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const [sslScan, setSslScan] = useState(false);
- [ ] Inline comment

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    let form = useForm<FormValuesType>({
- [ ] Change to a constant.
- [ ] Create an instance of not specify.

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +            TargetURL: "",
- [ ] camelCase

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const onSubmit = async (values: FormValuesType) => {
- [ ] Doc String

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    // Function to handle completion of output saving
- [ ] Doc string

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +    const handleSaveComplete = () => {
- [ ] doc string

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +        <form onSubmit={form.onSubmit(onSubmit)}>
- [ ] RenderComponent missing
- [ ] Dependency runtime missing

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
> +                    Start Nikto Scan
- [ ] <Button type={"submit"}>Start {title}</Button>

2024-04-28 07:57 UTC, bradleybogg commented on src/components/Nikto/Nikto.tsx
Look at a already baselined component for reference such as AirBase NG

2024-05-04 13:18 UTC, bradleybogg requested changes
- [x] Install dependency checker
- [ ] Fix merge conflicts

2024-05-07 14:45 UTC, michaeljpigott commented
@zkkok This one is ready for application testing.

2024-05-09 08:03 UTC, zkkok commented
Hi @SethJ1,
Please resolve the conflicts before application testing

2024-05-09 08:08 UTC, SethJ1 commented
@zkkok all done

2024-05-10 04:30 UTC, zkkok requested changes
@SethJ1 overall great work with the tool, basic functionality test passes. Just a slight change needed before it can be approved. The tool does not need root privileges, please modify it so that it does not use root commands.

2024-05-10 04:30 UTC, zkkok commented on src/components/Nikto/Nikto.tsx
> +        CommandHelper.runCommandWithPkexec("nikto", args, handleProcessData, handleProcessTermination)
Replace runCommandWithPkexec with runCommandGetPidAndOutput

2024-05-10 12:16 UTC, SethJ1 commented
@zkkok done

2024-05-12 11:42 UTC, zkkok requested changes
@SethJ1, functionality test looks good, tool worked as expected but the overlay does not show up while running the tool, please review your code again.

2024-05-13 03:12 UTC, SethJ1 commented
@zkkok I have fixed the overlay.

2024-05-14 07:15 UTC, zkkok approved these changes
The overlay works now

2024-05-15 00:36 UTC, merged