407 feature request fcrackzip tools
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #634
Opened 2024-04-24 05:52 UTC by namanbkshi

2024-04-28 08:18 UTC, bradleybogg requested changes
@namanbkshi 

Please complete a PR that reflects what has been changed.
https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/

2024-05-04 13:23 UTC, bradleybogg commented
No update on previous request.

2024-05-04 22:17 UTC, namanbkshi commented
> No update on previous request.

Hello Bradley ! This pull request was made for the implementation of feature request but in the weekly meeting I was told to implement the baseline as well in the same request. 

So perhaps you want me to create another pull request ?

2024-05-08 05:02 UTC, namanbkshi commented
Hi. I am done with the changes. Thanks in advance.

2024-05-12 02:52 UTC, michaeljpigott requested changes
Hi @namanbkshi 

There is a bit to work on here, including:
1. Ensuring you use the SaveOutputToTextFile_v2 component rather than SaveOutputToTextFile
2. Import the LoadingOverlayAndCancelButton component
3. Move the component constants to within the fcrackzip function 
4. Fix up the dependency checker

Kind regards 

Michael

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
>  import { SaveOutputToTextFile } from "../SaveOutputToFile/SaveOutputToTextFile";
As part of baselining, this should be changed to aveOutputToTextFile_v2. 
```suggestion
import { SaveOutputToTextFile_v2 } from "../SaveOutputToFile/SaveOutputToTextFile";
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
You are missing LoadingOverlayAndCancelButton.
```suggestion
import { LoadingOverlayAndCancelButton } from "../OverlayAndCancelButton/OverlayAndCancelButton";
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +// Component title
These component constants need to be moved to within the Fcrackzip function.

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +const description_guide = "Fcrackzip is a tool for cracking password of a protected zip file.";
Add the
```suggestion
const description_guide = "Fcrackzip is a tool for cracking the password of a protected zip file.";
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +    "Step 4: Click START CRACKING!";
Make this consistent with the actual button, which is Start Cracking!
```suggestion
    "Step 4: Click Start Cracking!";
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +    // Check for dependency availability when the component mounts
Full stop. 
```suggestion
    // Check for dependency availability when the component mounts.
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +        const isAvailable = await checkAllCommandsAvailability(dependencies);
This doesn't appear to be working in the app. Please test and review airbase-ng to see how the code should be implemented. 

To test, uninstall fcrackzip on your local machine, open DDT and navigate to the fcrackzip tool. If it is working, then the installation modal should open and ask you to install the dependency. 

It did not work for me after uninstalling fcrackzip.

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +                    <p>Dependency not available. Please install it.</p>
You should not need this once you get checkAllCommandsAvailability working correctly.

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +                    {SaveOutputToTextFile(output)}
This should be SaveOutputToTextFile_v2
```suggestion
                  {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
```

2024-05-12 02:52 UTC, michaeljpigott commented on src/components/Fcrackzip/Fcrackzip.tsx
> +                    <Button onClick={clearOutput}>Clear Output</Button>
Remove not required. 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/35479648/ddbb2570-e9cf-4ec9-ab82-477c42294fe5)

2024-05-14 11:02 UTC, namanbkshi commented
Hey Michael, I have implemented the changes the new commit. Thanks for your help.

2024-05-15 01:27 UTC, michaeljpigott approved these changes

2024-05-15 01:28 UTC, merged