Commit changes to dependencies, Tauri config, RouteWrapper, and add A…
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #642
Opened 2024-04-30 07:10 UTC by gurneetsi

This pull request contains the addition of arp finger print and modifications in dependencies.json, routewrapper and tauri.config

2024-05-04 08:20 UTC, JiatengTao commented
For reviewers' info, ARP Scan is different from ARP fingersprint
https://www.kali.org/tools/arp-scan/

2024-05-04 13:45 UTC, bradleybogg requested changes
Thank you for your work here.

There is some work to be done to ensure that this tool is baselined IAW all the other tools. 

Please review a completed baseline to ensure that you understand the requirements.

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +const ARPFingerprinting = () => {
Need to also add docstring

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +    );
Add doc string and inline comments

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +    };
Add docstring

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +export default ARPFingerprinting;
update name to reflect

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                    <Alert radius="md" children={"Scanning device at " + form.values.target_ip + "..."}></Alert>
remove alert functions

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                    <Alert radius="md" children={"Scanning device at " + form.values.target_ip + "..."}></Alert>
Update to camelCase

2024-05-04 13:45 UTC, bradleybogg commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                <TextInput label={"Target IP address"} required {...form.getInputProps("target_ip")} />
update to camelCase

2024-05-04 13:45 UTC, bradleybogg commented on src/components/RouteWrapper.tsx
> +
Update name to reflect the actual tool being implemented.

2024-05-07 02:24 UTC, gurneetsi commented
I have made the required changes into the file and, however in mentor meeting i was suggested to work upon arp-fingerprint instead of arp-scan as that is being covered by another team member. So, kindly consider it for arp fingerprint tool

2024-05-08 05:51 UTC, michaeljpigott requested changes
Hi there

Thanks for your hard work. I think you need to add the useEffect function to check if the command is available on the local machine. Check AirbaseNG to see how to implement. 

You also need to move the relevant constants to within the ARP Fingerprinting function. 

Kind regards Michael

2024-05-08 05:51 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +import { useCallback, useState } from "react";
You need to import useEffect so you can check if the command is available. 

- [ ] Import useEffect.

2024-05-08 05:51 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +    // Section: Callback Functions
You need to add useEffect to check if the command is available on the local machine. Check AirBase-NG for more information. 

- [ ] Add useEffect to see the command is available.

2024-05-08 05:51 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +            const result = await CommandHelper.runCommandWithPkexec(
Please confirm that you need elevated privileges to run this command. Otherwise, change to runCommandGetPidAndOutput.

2024-05-12 05:06 UTC, michaeljpigott requested changes
Hi @gurneetsi 

There's a bit to work on here. You need to replace SaveOutputToTextFile with SaveOutputToTextFile_v2 and implement the LoadingOverlayAndCancelButtonPkexec component. 

Kind regards

Michael

2024-05-12 05:06 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                <Stack>
This is where you need the OverlayandCancelButtonPkexec component.

2024-05-12 05:06 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                    <TextInput label="Target IP Address" required {...form.getInputProps("targetIP")} />
Lowercase a. 
```suggestion
                    <TextInput label="Target IP address" required {...form.getInputProps("targetIP")} />
```

2024-05-12 05:06 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                    {SaveOutputToTextFile(output)}
As previously mentioned, this should be SaveOutputToTextFile_v2
```suggestion
                 {SaveOutputToTextFile_v2(output, allowSave, hasSaved, handleSaveComplete)}
```

2024-05-12 05:06 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                        {isScanning ? "Scanning..." : "Scan"}
You probably do not need this once you implement the OverlayandCancelButtonPkexec component.

2024-05-14 23:30 UTC, michaeljpigott requested changes
Hi @gurneetsi 

It is looking a lot better. Just a couple of things to do with adding the state variable to store the process ID of the command argument, and then adding this variable as an argument to LoadingOverlayAndCancelButton. 

Also, do not forget to change address to lowercase a in your text input label. 

Kind regards

Michael

2024-05-14 23:30 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +
You need to add a constant to store the process ID of the command execution. 
```suggestion
 const [pid, setPid] = useState(""); // State variable to store the process ID of the command execution.
```

2024-05-14 23:30 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                    {LoadingOverlayAndCancelButton(loading, "")}
The second argument for LoadingOverlayAndCancelButton should be the pid. 
```suggestion
                    {LoadingOverlayAndCancelButton(loading, pid)}
```

2024-05-14 23:30 UTC, michaeljpigott commented on src/components/arpfingerprint/arpfingerprint.tsx
> +                        <TextInput label="Target IP Address" required {...form.getInputProps("targetIP")} />
Still need lowercase a for address. 
```suggestion
                        <TextInput label="Target IP address" required {...form.getInputProps("targetIP")} />
```

2024-05-15 02:17 UTC, michaeljpigott approved these changes

2024-05-15 02:18 UTC, merged