594 bug fix baseline johntheripper
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #649
Opened 2024-05-02 12:27 UTC by slpysiren

Completed the baseline checklist for the component. Please let me know if I missed anything or need to make any changes.

2024-05-04 15:26 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +    const [selectedIncrementOption, setSelectedIncrementOption] = useState(""); // State variable to store the selected increment order.
These are all react state hooks as indicated by the "useState". Please move them into that appropriate section. 
```suggestion
```

2024-05-04 15:26 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +    const [hasSaved, setHasSaved] = useState(false); // State variable to indicate if the output has been saved.
```suggestion
    const [hasSaved, setHasSaved] = useState(false); // State variable to indicate if the output has been saved.
    const [selectedFileTypeOption, setSelectedFileTypeOption] = useState(""); // State variable to store the selected file type.
    const [selectedModeOption, setSelectedModeOption] = useState(""); // State variable to store the selected crack mode.
    const [selectedIncrementOption, setSelectedIncrementOption] = useState(""); // State variable to store the selected increment order.

```

2024-05-04 15:27 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        // Increment orders
Remove this comment.

2024-05-04 15:29 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        "Step 2: Specify the hashing algorithm used by the password you are trying to crack (e.g md5). For a full list of options, open new terminal and use john --list=formats command.\n" +
```suggestion
        "Step 2: Specify the hashing algorithm used by the password you are trying to crack (e.g md5).\n" +
```

2024-05-04 15:29 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        "Step 3: Specify which cracking mode to use.\n" +
```suggestion
        "Step 3: Specify the cracking mode to use.\n" +
```

2024-05-04 15:29 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        "Step 4: Select the file type of the password file.\n" +
```suggestion
        "Step 4: Select the file type.\n" +
```

2024-05-04 15:30 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        "Step 6: Click crack to commence the tool's execution.\n" +
```suggestion
        "Step 6: Click 'Start John the Ripper'.\n" +
```

2024-05-04 15:30 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> +        "Step 7: View the output block to view the results of the tool's execution.\n";
```suggestion
        "Step 7: View the output block to view the results of the tools execution.\n";
```

2024-05-04 15:32 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
>              //Crack the extracted hash
```suggestion
            // Crack the extracted hash
```

2024-05-04 15:34 UTC, bradleybogg commented on src/components/JohnTheRipper/JohnTheRipper.tsx
>              try {
Update this block to use the overlay for cancelling

2024-05-04 15:37 UTC, bradleybogg requested changes
Very good work @slpysiren

I appreciate your efforts in doing it right and taking the time to do so.
Good work on this one. I have some very minor changes to make. Some of the comments for steps I've added reccomendations. See which you think is better. For the others please implement changes.

Thank you!

2024-05-10 06:41 UTC, michaeljpigott approved these changes
Hi @slpysiren 

This baselining work looks good. I approve to merge pending app testing from @zkkok 

Kind regards

Michael

2024-05-11 11:29 UTC, zkkok requested changes
Hi @slpysiren, Application testing has been done. There's a few issues but most of them pre-existed within the component. Only need to make some minor changes before it can be merged.

Summary of functionality test:
[Functionlity Testing(John).pdf](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/files/15282610/Functionlity.Testing.John.pdf)

2024-05-11 11:29 UTC, zkkok commented on src/components/JohnTheRipper/JohnTheRipper.tsx
>  import { Button, LoadingOverlay, NativeSelect, Stack, TextInput } from "@mantine/core";
Remove unused imports

2024-05-11 11:29 UTC, zkkok commented on src/components/JohnTheRipper/JohnTheRipper.tsx
> + * Represents the form values for the AirbaseNG component.
Revise comment

2024-05-12 22:48 UTC, michaeljpigott commented
Hi @zkkok, I will let you review your requested changes for this one. 

Thanks.

2024-05-14 06:56 UTC, zkkok approved these changes
Baseline bug fix looks good without any issue in sight.

2024-05-15 00:28 UTC, merged