502 feature request netcat listen and connect
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #653
Opened 2024-05-03 08:59 UTC by basoreeper3007

**### Feature Implementations**
-Added Listen mode to make the machine listen for connections on a specified port.
-Added Connect mode to act as the connector that connects to an existing listener.

2024-05-04 16:01 UTC, bradleybogg requested changes
<img width="344" alt="image" src="https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/62839826/c843f411-ac92-4736-9ea6-01ac0d3cff34">
<img width="643" alt="image" src="https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/62839826/38b92900-9b2e-42c5-9d1c-67b5bb70abbf">


Hi @basoreeper3007 

I have attempted to run the code. As seen in first image there is no error.
Second image there is an error that is not replicated within the standard terminal.

Please investigate.

2024-05-05 03:29 UTC, basoreeper3007 commented
@bradleybogg I have fixed the syntax bug with the Connect feature.

2024-05-05 09:47 UTC, michaeljpigott requested changes
Hi there, 

I have tested Netcat on my local computer and it works. I am not sure exactly why you need to use bash to use the connect functionality, so it would be good to add a comment. 

I am interested to know why there are backticks in the initial setting of the args variable. It does seem a bit strange, but I know that isn't your code. 

I also recommend removing the original CommandHelper line in the connect case now that it is commented out.

2024-05-05 09:47 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +                //CommandHelper.runCommandGetPidAndOutput("nc", args, handleProcessData, handleProcessTermination)
Since you are not using this line, please delete. 

- [ ] Delete commented out line.

2024-05-05 09:47 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +                    "bash",
I am not sure why you need to use bash here. The command nc <IP address> <port> should work without bash. It's probably worth a comment to explain. 

- [ ] Comment required to explain the use of bash.

2024-05-05 09:47 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
>          let args = [``];
Not sure why there are backticks. Have you tried what happens when you remove them and leave it as an empty array?

2024-05-06 09:43 UTC, basoreeper3007 commented
@michaeljpigott I removed the comment line that wasn't being used. The connect feature can run without bash, I only used it as it helped me avoid syntax errors (see my comment). I left a comment explaining why I used bash there. The backticks don't need to be in the args[] initialization, so I took them out (that was from the previous student).

2024-05-06 23:13 UTC, michaeljpigott approved these changes
Thank you Bas for making those changes. Your commit comments were excellent and easy to follow. 

I approve for this pull request to be merged into main pending approval from the application testers. 

Kind regards 

Michael

2024-05-07 07:52 UTC, merged