641 feature request gitleak tool integration
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #654
Opened 2024-05-03 16:50 UTC by chandelshubham63

This **PR** is for new tool _**Gitleaks**_ integration in DDT, enhancing security testing capabilities. Gitleaks scans Git repositories for sensitive information leaks, providing crucial insights into potential security risks.
The integration allows users to specify the **repository path** and provides an **advanced mode** for additional **Git log** options and **report file path customization.**

**Testing-**
I tested it and it worked perfectly, ensuring accurate detection of sensitive information leaks.

**How to use-** 
To utilize, specify the repository path and optionally provide advanced settings for more detailed control.

2024-05-04 16:03 UTC, bradleybogg requested changes
Please resolve merge conflict before I review.

2024-05-08 06:40 UTC, michaeljpigott requested changes
Hi there

This is looking really good. I only have one recommended change, which is to add a full stop to the description in RouteWrapper.tsx. 

Good work. Make this change and we'll arrange some application testing. 

Kind regards

Michael

2024-05-08 06:40 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> +        description: "Detect hardcoded secrets in git repositories",
Need a full stop at the end of the sentence. 

- [ ] Add full stop.

2024-05-08 08:54 UTC, michaeljpigott commented
Hey @chandelshubham63 

I am getting an error message even though the code has run. The message probably should be "Processed completed successfully". Can you please investigate? 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/35479648/8e83d52d-6588-4a89-adab-2429af1d7aaf)

2024-05-08 12:38 UTC, chandelshubham63 commented
Hi @michaeljpigott, just wanted to clarify that `**gitleaks**` typically returns exit code 1 to indicate findings (leaks) in the repository, not necessarily an error. This is part of its normal behavior, as it's designed to alert users about potential sensitive information. So, while the process did complete, the exit code 1 signifies the presence of leaks that require attention rather than an error. Let me know if you have any further questions!

2024-05-08 15:21 UTC, michaeljpigott approved these changes
Hi @chandelshubham63 

Thank you for clarifying about the exit code. 

I have tested the tool in the app and appears to work well. 

Kind regards

Michael

2024-05-08 15:22 UTC, merged