582-bug-fix-baseline-dnsmap
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #664
Opened 2024-05-07 08:08 UTC by Cyriacjose

Using Rendercomponent instead of user guide
Adding inline and other important comments
Aligning Code for better presentation and removing some structure and grammar issues

2024-05-11 02:36 UTC, michaeljpigott requested changes
Hi @Cyriacjose 

This is looking good. You need to add the checkAllCommandsAvailability and InstallationModal components so DDT checks to see if dnsmap has been installed. Refer to Airbase-ng for reference. 

Kind regards

Michael

2024-05-11 02:36 UTC, michaeljpigott commented on src/components/DNSMap/DNSMap.tsx
You need to import checkAllCommandsAvailability. See Airbase-NG for reference.

2024-05-11 02:36 UTC, michaeljpigott commented on src/components/DNSMap/DNSMap.tsx
You need to import InstallationModal. See Airbase-NG for reference.

2024-05-11 02:36 UTC, michaeljpigott commented on src/components/DNSMap/DNSMap.tsx
> +    const title = "DNS Mapping for Subdomains (DNSMap)";
Need to match the title with what's on Kali.org, so it should be Dnsmap. 
```suggestion
    const title = "Dnsmap";
```

2024-05-11 02:36 UTC, michaeljpigott commented on src/components/DNSMap/DNSMap.tsx
> +    const dependencies = ["DNSMap"]; // Contains the dependencies required by the component.
Should be all lowercase. Needs to match the command entered into the terminal. 
```suggestion
    const dependencies = ["dnsmap"]; // Contains the dependencies required by the component.
```

2024-05-11 02:36 UTC, michaeljpigott commented on src/components/DNSMap/DNSMap.tsx
> +            <form onSubmit={form.onSubmit(onSubmit)}>
Need to add the loadingModal here. Refer to Airbase-ng.

2024-05-11 02:37 UTC, michaeljpigott commented
@Cyriacjose Can you also please add the issue that you are working on to this pull request?

2024-05-11 08:03 UTC, Cyriacjose commented
Fix for Issue: Bug Fix (Baseline): DNSMap

2024-05-12 03:03 UTC, michaeljpigott requested changes
Hi @Cyriacjose 

Good work. You just need to implement the checkAllCommandsAvailability in your code. Refer to airbase-ng to see how to do it. 

Kind regards

Michael

2024-05-12 06:09 UTC, michaeljpigott approved these changes

2024-05-12 06:10 UTC, merged