Updated baseline for Rainbowcrack
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #665
Opened 2024-05-07 08:18 UTC by Siddh2001

This pull request addresses several bugs fixes within the component.
Here's a checklist which was followed while doing so :
All unused imports have been removed
Every interface has an appropriate docstring
The FormValuesType interface is located outside of the main component
The FormValuesType interface is named correctly
Every variable in the FormValuesType interface is using camelCase convention
Every function has an appropriate docstring
All component state variables are using camelCase 
There exist logical sections within the variable and constant definitions for both state and basic
All constants have camelCase
Every React hook has an appropriate inline comment
Every component constant has an appropriate inline comment
The title contains only the tool name limited to its source documentation.
The description contains only the description of the tool from the source documentation.
The steps contains only those applicable to those features implemented
The steps formatting is as expected (no extraneous new lines)
The sourceLink contains the link to the source component (NEEDS TO BE ADDED)
The tutorial contains an empty string 
The dependencies contain those of the required package
All constants including title and description are free of grammar issues
The form is clearly defined including comment
The useEffect is clearly defined including comments 
Dependencies components installed
Handle Process Data exists and is clearly defined with docstring and comments
Handle process termination exists and is clearly defined with docstring and comments
The onSubmit function is clearly defined and has comments and doc strings
The clearOutput is clearly defined and free from errors
The outputV2 is clearly defined and in use
The Render component is in use within the return of the component function
The component function is not exported
The component has a default export of the function
The code is free of all errors both logical and run time
The component is tested. Any logical errors are raised in a new Trello Card and a Github issue raised that clearly identifies the fault found and how to reproduce. (NONE)
The component is free from all grammar issues.
Trello is updated completely with the status of my request.

Please reach out if any issues are experienced.

2024-05-11 03:06 UTC, michaeljpigott requested changes
Hi @Siddh2001

Good work. Please implement my suggested changes. They are mainly around using SaveOutputToTextFile_v2 because it is a required part of baselining, as well ensuring the dependencies constant matches with the actual name of the command. 

Also, I do not believe the rcrack command requires escalated privleges:
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/35479648/90b20926-cb68-48f8-a4da-229a01bf882c)


Kind regards

Michael

2024-05-11 03:06 UTC, michaeljpigott commented on src/components/Rainbowcrack/Rainbowcrack.tsx
> +    const dependencies = ["rainbowcrack"]; // Dependencies required by the component.
This needs to be rcrack to match with the actual command. Otherwise the installationModal keeps popping up.

2024-05-14 07:15 UTC, Siddh2001 commented
Waiting for review

2024-05-15 01:18 UTC, michaeljpigott commented
Hi @Siddh2001, good work on making those changes. I realised that rainbowcrack needs to be the name of the dependency, so I changed it back. There seems to be an issue when the name of the command does not match the name of the application that is installed. I have logged issue #692 to further investigate this issue in the future.

2024-05-15 01:18 UTC, michaeljpigott approved these changes

2024-05-15 01:19 UTC, merged