Applied changes according to the baseline checklist for CVE 2021-41773.tsx
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #667
Opened 2024-05-07 11:31 UTC by hhenryDeakin

I created changes here in order to meet the standards for the CVE 2021-41773 baseline checklist: 18057f7c2f264f726f6b98426294ac5ba8360754

If there are any details that I am missing or things that I need to include, please let me know so that I can work on them ASAP and get it back to you in a timely manner (before the cut off date of this trimester).

2024-05-11 03:43 UTC, michaeljpigott requested changes
Hi @hhenryDeakin 

Overall this is looking good. Please move your components to within the function itself. 

I am pretty sure the dependency constant should be python3 because that's the tool which runs the exploit. 

Please confirm that you need root access to run the exploit otherwise use runCommandGetPidAndOutput. 

Kind regards

Michael

2024-05-11 03:43 UTC, michaeljpigott commented on src/components/CVE-2021-41773/CVE-2021-41773.tsx
> +// Component Constants.
Component constants should be moved to within the CVE202141773 function.

2024-05-11 03:43 UTC, michaeljpigott commented on src/components/CVE-2021-41773/CVE-2021-41773.tsx
>      "Step 6: View the Output block below to view the results of the attack vectors execution.";
Vectors is missing an apostrophe. 
```suggestion
    "Step 6: View the Output block below to view the results of the attack vector's execution.";
```

2024-05-11 03:43 UTC, michaeljpigott commented on src/components/CVE-2021-41773/CVE-2021-41773.tsx
> +const dependencies = ["CVE 2021-41773"]; // Contains the dependencies required by the component.
I do not think CVE 2021-41773 is the dependency. It should be python3. 
```suggestion
const dependencies = ["python3"]; // Contains the dependencies required by the component.
```

2024-05-11 03:43 UTC, michaeljpigott commented on src/components/CVE-2021-41773/CVE-2021-41773.tsx
> +        CommandHelper.runCommandWithPkexec("python3", args, handleProcessData, handleProcessTermination)
Please confirm that you need root access to run this command. Otherwise change to runCommandGetPidAndOutput.

2024-05-13 10:55 UTC, hhenryDeakin commented
Hi @michaeljpigott 

Your requested changes have been completed and pushed. All checks have passed. This bugfix baseline is ready for review again when you are ready.

Thanks.

2024-05-15 00:23 UTC, michaeljpigott approved these changes

2024-05-15 00:23 UTC, merged