602 bug fix baseline rtsort
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #676
Opened 2024-05-10 02:04 UTC by anjojoseph

Hi Michael/Team,
Completed the baseline bugfix checklist for the RTSort tool.
Tool is working as expected.
Kindly review and merge the pull request.
Thank you

2024-05-11 04:51 UTC, michaeljpigott reviewed
Hi @anjojoseph 

Looks good. Just a few minor changes required. 

Kind regards

Michael

2024-05-11 04:51 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
>  // Funtion for implementing RTSort as GUI component
Typo in the comment. 
```suggestion
// Function for implementing RTSort as GUI component
```

2024-05-11 04:51 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +
Delete this blank line.

2024-05-11 04:51 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +    const description = "RTSort is a subfuntion of the Rainbow Crack tool. This function sorts created rainbow tables."; // Description of the component.
Typos:
```suggestion
    const description = "RTSort is a sub-function of the Rainbowcrack tool. This function sorts created rainbow tables."; // Description of the component.
```

2024-05-11 04:51 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +        "Step 3: View the output block to view the results of the tools execution.\n";
Need an apostrophe. 
```suggestion
        "Step 3: View the output block to view the results of the tool's execution.\n";
```

2024-05-11 04:51 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +    const dependencies = ["rainbowcrack"]; // Contains the dependencies required by the component.
The dependency is rcrack

2024-05-11 04:56 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +                    <br></br>
Please delete.

2024-05-12 02:52 UTC, anjojoseph commented
Working on the suggested changes

2024-05-12 03:32 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
>  // Funtion for implementing RTSort as GUI component
done

2024-05-12 03:32 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
> +
done

2024-05-12 03:33 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
> +    const description = "RTSort is a subfuntion of the Rainbow Crack tool. This function sorts created rainbow tables."; // Description of the component.
done

2024-05-12 03:33 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
> +        "Step 3: View the output block to view the results of the tools execution.\n";
done

2024-05-12 03:33 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
> +    const dependencies = ["rainbowcrack"]; // Contains the dependencies required by the component.
done

2024-05-12 03:34 UTC, anjojoseph commented
All changes have been implemented.
Kindly review from you end.
Thankyou

2024-05-12 04:27 UTC, michaeljpigott requested changes
Hi @anjojoseph 

You missed one of the typos. Otherwise it looks good. 

Kind regards

Michael

2024-05-12 04:27 UTC, michaeljpigott commented on src/components/RTsort/RTsort.tsx
> +    const description = "RTSort is a sub-funtion of the Rainbowcrack tool. This function sorts created rainbow tables."; // Description of the component.
Still got a typo in there. 
```suggestion
    const description = "RTSort is a sub-function of the Rainbowcrack tool. This function sorts created rainbow tables."; // Description of the component.
```

2024-05-12 04:34 UTC, anjojoseph commented on src/components/RTsort/RTsort.tsx
> +    const description = "RTSort is a sub-funtion of the Rainbowcrack tool. This function sorts created rainbow tables."; // Description of the component.
updated

2024-05-12 04:35 UTC, anjojoseph commented
Hi Michael,
thank you the typo has been corrected.
Kindly review.
Thankyou

2024-05-12 05:16 UTC, michaeljpigott approved these changes

2024-05-12 05:18 UTC, merged