my first edit on smbEnumration
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #738
Opened 2024-08-10 19:30 UTC by SHAHAD908

2024-08-15 23:30 UTC, michaeljpigott requested changes
Hi @SHAHAD908 

I have recommended quite a lot of changes because you have yet to baseline SMBEnumeration. 

Please implemented my requested changes and push back to this branch. 

Also, can you please add the following: 
* A more description title (should have baseline in the name)
* A description
* More descriptive commits - see [this guide](https://www.freecodecamp.org/news/how-to-write-better-git-commit-messages/) to learn how to write commit messages. 
* Link this pull request to the relevant GitHub issue. 

Please contact me if you have any questions. 

Kind regards

Michael

2024-08-15 23:30 UTC, michaeljpigott commented on src/components/SMBEnumeration/SMBEnumeration.tsx
> +                {UserGuide(title, descriptionUserGuide)}
Can delete this line. UserGuide not required as part of baseline. 
```suggestion
              
```

2024-08-15 23:30 UTC, michaeljpigott commented on src/components/SMBEnumeration/SMBEnumeration.tsx
>                  <TextInput label={"Target IP or Hostname"} required {...form.getInputProps("ip")} />
Lowercase h. 
```suggestion
                <TextInput label={"Target IP or hostname"} required {...form.getInputProps("ip")} />
```

2024-08-15 23:30 UTC, michaeljpigott commented on src/components/SMBEnumeration/SMBEnumeration.tsx
>                      label={"Scan Speed"}
Lowercase s. 
```suggestion
                    label={"Scan speed"}
```

2024-08-15 23:30 UTC, michaeljpigott commented on src/components/SMBEnumeration/SMBEnumeration.tsx
>                      label={"SMB Script"}
Lowercase s. 
```suggestion
                    label={"SMB script"}
```

2024-08-15 23:30 UTC, michaeljpigott commented on src/components/SMBEnumeration/SMBEnumeration.tsx
>                  <Button type={"submit"}>Scan</Button>
The format of the button should be Start <name of tool>
```suggestion
                <Button type={"submit"}>Start {title}</Button>
```

2024-09-13 06:35 UTC, michaeljpigott commented
Hi @SHAHAD908 and @ZIHRAN1 

Now that pull request #853 has been merged into main, does SMBEnumeration still require baselining and do you still require this pull request? 

Kind regards 

Michael

2024-09-13 23:43 UTC, michaeljpigott commented
Placing this pull request on hold while await confirmation about its status from @SHAHAD908 and @ZIHRAN1

2024-09-26 11:24 UTC, Bipan079 commented
I was having a look at this pull request.
I will try reaching out to @SHAHAD908  on teams regarding this pull request.

2025-03-05 15:33 UTC, closed without merging