761 bug ip address field has no input validattion
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #768
Opened 2024-08-20 11:59 UTC by s223915833

Added Form validations and back end validations for IP address.

2024-08-21 09:26 UTC, michaeljpigott commented
Hi @s223915833, it looks like you need to `yarn run style' because it is failing the CI check.

2024-09-01 15:42 UTC, Oliver2049 commented
Hi @s223915833,  
Can you run 'yarn run style' and the 'npx prettier -w <file path>' so it can pass CI?

2024-09-04 03:17 UTC, s223915833 commented
Can you please check now. @michaeljpigott @Oliver2049 Thank you!

2024-09-08 02:35 UTC, michaeljpigott commented
@s223915833 can you please resolve the conflict?

2024-09-12 05:06 UTC, michaeljpigott requested changes
Hi @s223915833 

You need to update RouteWrapper.tsx so it is referring to SMBGhostScanner rather than SMGGhostScanner, otherwise DDT crashes.

Kind regards

Michael

2024-09-14 00:25 UTC, michaeljpigott commented
Hi @s223915833 

I changed the label to "Awaiting Assignee Update" because I am still waiting for you to fix the issue with routeWrapper.tsx. 

Kind regards

Michael

2025-03-06 02:46 UTC, GoldenBanksia commented
PR request closed as author unable to be contacted to submit requested changes. 

Issue reopened as Bug #1130 as validation check still outstanding for this tool.

2025-03-06 02:46 UTC, closed without merging