Baseline Netcat #598
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #783
Opened 2024-08-23 01:25 UTC by Oliver2049

- Added required imports
- Added the appropriate docstring to the functions and interface
- Changed the state variables to camelCase
- Added inline comments to all react hooks and to all component constant
- Removed the Userguide(title,description_userguide) in Stack as it is no longer required
- Added the steps for user guide in component description
- Add required component state variables
- Added sourceLink and updated it with the appropriate link
- Added empty string in tutorial
- Fixed grammar issues
- Added the function handleSaveComplete with appropriate comments and docstring
- Added the render component for user guide which was not there in the code

2024-08-30 02:46 UTC, michaeljpigott requested changes
Hi @Oliver2049 

Overall it is lookingi pretty good. Just need to make minor changes, including using the Step 1:, Step 2:, etc format. 

Kind regards

Michael

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Netcat is a powerful tool that is used to connect two machines together for communication and for other uses."; // Description of the component.
The use of the word "powerful" makes it sound like advertising. I suggest copying the description from the [netcat Kali page](https://www.kali.org/tools/netcat/). 
```suggestion
        "A simple Unix utility which reads and writes data across network connections using TCP or UDP protocol. "; // Description of the component.
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to listen for connections for chat or reverse shell choose the Interactive shell/Listen option and provide \n a port number.\n" +
The format for this should be Step 1: blah, Step 2: blah. Refer to a tool like WhatWeb for an example.

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "How to use this netcat tool:\n" +
Capitalise Netcat and remove the word "tool". 
```suggestion
        "How to use this Netcat:\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to listen for connections for chat or reverse shell choose the Interactive shell/Listen option and provide \n a port number.\n" +
Lowercase i for interactive and lowercase l for listen. 
```suggestion
        "- If you want to listen for connections for chat or reverse shell choose the interactive shell/listen option and provide \n a port number.\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to send a file, provide the destination IP address, Port number, and File name\n" +
Lowercase p for port. Lowercase f for file.
```suggestion
        "- If you want to send a file, provide the destination IP address, port number, and file name\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to receive a file, provide a port number and the File name.\n" +
Lowercase f for file. 
```suggestion
        "- If you want to receive a file, provide a port number and the file name.\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to port scan a domain, provide Domain name and a Port number. \n" +
Lowercase d for domain, lowercase p for port. 
```suggestion
        "- If you want to port scan a domain, provide domain name and a port number. \n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Note: You should only use website port scan to a domain that you own.\n" +
Change "to" to "on". Add "the" and "option" to either side of "website port scan". 
```suggestion
        "Note: You should only use the website port scan option on a domain that you own.\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Note 2: Using the sending/receiving file option might seem like it is not working, but it is working.\n" +
More information required. How do you know if it is working?

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "You will need a second machine to see the file transfer\n" +
Full stop. 
```suggestion
        "You will need a second machine to see the file transfer.\n" +
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "For more information go to the reference page and click on netcat, alternatively Google is your friend.";
Comma, capital N for Netcat. It would be great to link to the reference page from here. I do not like the reference to Google here. PT-GUI is meant to be making things easier, not encouraging people to do their own research. 
```suggestion
        "For more information, go to the reference page and click on Netcat.";
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +    const sourceLink = "https://github.com/openbsd/src/blob/master/usr.bin/nc/netcat.c"; // Link to the source code
Not sure if this is the right link. The reference page links to https://www.kali.org/tools/netcat/

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +
useEffect component should go here to check for dependencies. 
```suggestion

 // Check if the command is available and set the state variables accordingly.
    useEffect(() => {
        // Check if the command is available and set the state variables accordingly.
        checkAllCommandsAvailability(dependencies)
            .then((isAvailable) => {
                setIsCommandAvailable(isAvailable); // Set the command availability state
                setOpened(!isAvailable); // Set the modal state to opened if the command is not available
                setLoadingModal(false); // Set loading to false after the check is done
            })
            .catch((error) => {
                console.error("An error occurred:", error);
                setLoadingModal(false); // Also set loading to false in case of error
            });
    }, []);
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +    const dependencies = ["netcat"]; // Contains the dependencies required by the component
This should be netcat-traditional.
```suggestion
    const dependencies = ["netcat-traditional"]; // Contains the dependencies required by the component
```

2024-08-30 02:46 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +                    <Button type={"submit"}>start netcat</Button>
Capital S for start and you can just use the variable for the title. 
```suggestion
                    <Button type={"submit"}>Start {Title}</Button>
```

2024-08-31 01:38 UTC, Oliver2049 commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to listen for connections for chat or reverse shell choose the Interactive shell/Listen option and provide \n a port number.\n" +
I'm still thinking about the word "Option" for the description of this tool as for this tool, you just need to choose between the options and not really follow any steps to start.

2024-08-31 02:20 UTC, Oliver2049 commented on src/components/Netcat/Netcat.tsx
> +        "- If you want to listen for connections for chat or reverse shell choose the Interactive shell/Listen option and provide \n a port number.\n" +
I changed to Step and update the description a little

2024-09-02 06:03 UTC, michaeljpigott requested changes
Hi @Oliver2049 

Very good work. Just some more minor changes. My apologies for telling you the wrong dependency - it should be nc rather than nc-traditional. 

Kind regards

Michael

2024-09-02 06:03 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +    const dependencies = ["netcat-traditional"]; // Contains the dependencies required by the component
Sorry Oliver this is my bad. It should reflect the command, therefore it should be nc. :-(
```suggestion
    const dependencies = ["nc"]; // Contains the dependencies required by the component
```

2024-09-12 05:09 UTC, michaeljpigott commented
Hi @Oliver2049 I am still waiting for you to implement the requested changes. 

Kind regards

Michael

2024-09-14 00:21 UTC, michaeljpigott requested changes
Hi @Oliver2049 

Looking really good. Just three more very minor changes requested. 

Kind regards

Michael

2024-09-14 00:21 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Step 2: If you want to scan for ports, provide an IP address and a port range\n" +
Need a full stop. 
```suggestion
        "Step 2: If you want to scan for ports, provide an IP address and a port range.\n" +
```

2024-09-14 00:21 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Step 3: If you want to send a file, provide the destination IP address, port number, and file name\n" +
Need a full stop. 
```suggestion
        "Step 3: If you want to send a file, provide the destination IP address, port number, and file name.\n" +
```

2024-09-14 00:21 UTC, michaeljpigott commented on src/components/Netcat/Netcat.tsx
> +        "Note:   You should only use website port scan to a domain that you own.\n" +
On rather than to. 
```suggestion
        "Note:   You should only use website port scan on a domain that you own.\n" +
```

2024-09-15 23:29 UTC, michaeljpigott approved these changes
Hi @Oliver2049 

Thank you for making those changes. I approve this pull request. 

Kind regards

Michael

2024-09-15 23:31 UTC, merged