791 feature request unicornscan tool implementation
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #818
Opened 2024-08-31 05:18 UTC by SethJ1

2024-09-02 04:29 UTC, michaeljpigott requested changes
Hi @SethJ1 

This is looking really good. I just found that the loading overlay was not appearing when I ran the tool, and the actual command itself wasn't appearing in the output block. 

I have made a couple of suggestions, which I think may fix these problems. 

Kind regards

Michael

2024-09-02 04:29 UTC, michaeljpigott commented on src/components/Unicornscan/Unicornscan.tsx
> +            .then(() => {
I found that you need to add the output and pid variables here to show the command in the output block. 
```suggestion
            .then(( { output, pid } ) => {
```

2024-09-02 04:29 UTC, michaeljpigott commented on src/components/Unicornscan/Unicornscan.tsx
> +                setLoading(false);
I found that the loadingOverlayAndCancel screen was not appearing, so copied Aircrack-NG, which also uses runCommandWithPkexec. I found that once I made these changes, the loading screen started to appear. 
```suggestion
               setOutput(output);
                setAllowSave(true);
                setPid(pid);
```

2024-09-02 04:29 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> +            "Unicornscan is essential for scanning servers and hosts to see what available ports are being utilized for network communications.",
Changed to Australian spelling - utilised with an "s". 
```suggestion
            "Unicornscan is essential for scanning servers and hosts to see what available ports are being utilised for network communications.",
```

2024-09-02 04:29 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> +        category: "Network Scanning",
I think this should be Network Scanning and Enumeration. 
```suggestion
        category: "Network Scanning and Enumeration",
```

2024-09-11 23:55 UTC, michaeljpigott reviewed
Hi @SethJ1 

Thank you for making those changes. 

I just noticed that when I enter Metasploitable's IP address into the IP address field and choose TCP Scan, nothing appears to happen:

![image](https://github.com/user-attachments/assets/84fbf34f-70be-4112-9983-8c019b4d782a)

The same thing happens when I enter the exact same command into the Terminal. 

I wonder if it needs some extra parameter for it to run? I noticed on the [Kali page](https://www.kali.org/tools/unicornscan/), it has "a" after  the IP address:

![image](https://github.com/user-attachments/assets/d2debc8b-17d4-46d2-b9d8-14dabad6eee2)

Kind regards

Michael

2024-09-14 01:27 UTC, SethJ1 commented
Sorry @michaeljpigott it seems when I was testing the tool I used Verbose mode every time not realising that without that it wont actually show any of the ports. I have made it so that now it is always in interactive verbose mode. The 'a' flag selects all ports on the IP which is usually default but I shouldn't need it as I have a field to select the port range. Thankyou.

2024-09-14 01:45 UTC, michaeljpigott approved these changes
Hi @SethJ1 

Thank you for making that change. I have tested and the tool works well. I approve this pull request. 

Kind regards

Michael

2024-09-14 01:45 UTC, merged