830-FEATURE-REQUEST-RAINBOWCRACK
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #832
Opened 2024-09-03 04:42 UTC by abasb123

Improved User experience (UX) by implementing Real-time hash validation, helps users from entering invalid or incorrectly formatted hash values, reducing errors in processing. This also prevent unnecessary execution error or crashes and validate hash value before attempt.

2024-09-04 05:29 UTC, michaeljpigott commented
Hi @abasb123 

Why do you want to merge this into [830-feature-request-enhanced-ux-for-rainbowcrack-tool](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/tree/830-feature-request-enhanced-ux-for-rainbowcrack-tool) rather than main? 

Kind regards 

Michael

2024-09-05 04:08 UTC, abasb123 commented
Hi @michaeljpigott ,
I have changed the branch to main. 
Kind regards,
Abbas.

2024-09-12 05:42 UTC, michaeljpigott requested changes
Hi @abasb123 

Can you please provide the steps of how you got this tool to work? 

Although your validation is very good, I believe this tool will only work if you add the parameters `. -h` before the hash, which your validation method does not like. 

![image](https://github.com/user-attachments/assets/3744c80c-0f1a-416f-8b4d-aa2e2f028662)

Kind regards 

Michael

2024-09-14 03:08 UTC, abasb123 commented
> Hi @abasb123
> 
> Can you please provide the steps of how you got this tool to work?
> 
> Although your validation is very good, I believe this tool will only work if you add the parameters `. -h` before the hash, which your validation method does not like.
> 
> ![image](https://private-user-images.githubusercontent.com/35479648/366735159-3744c80c-0f1a-416f-8b4d-aa2e2f028662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODI2NTcsIm5iZiI6MTcyNjI4MjM1NywicGF0aCI6Ii8zNTQ3OTY0OC8zNjY3MzUxNTktMzc0NGM4MGMtMGYxYS00MTZmLThiNGQtYWEyZTJmMDI4NjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAyNTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OTAyYThmYmE0MWQ3OGQ4ODE3MzA0ZjZiMmM3NDgxNzAwZmM2OTNmZWI4OGQzZWJkMjhmNmRkYTE4OTY4MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoGf8Od6i0UkV42x-uYJaSy32R2eaTMP9aIzBQqfF1E)
> 
> Kind regards
> 
> Michael

Hi @michaeljpigott ,
I have implemented a real-time hash validation feature to ensure that users input valid hash values. This validation checks if the hash matches common formats (e.g., MD5, SHA-1), ensuring that incorrect inputs don’t get processed. 
To use the tool :
In the RainbowCrack tool, enter the hash you want to crack. The tool will automatically validate your hash in real-time.

If you believe the validation should accept parameters like .-h, we can adjust the validation to accept these flags or modify the command that gets sent for cracking.

2024-09-14 23:40 UTC, michaeljpigott requested changes
Hi @abasb123 

I think my point about the validation is that tool does not work with it. 

Although the validation is a great initiative, can you please ensure the tool still functions. 

Kind regards

Michael

2025-03-06 03:46 UTC, GoldenBanksia commented
PR closed as author unable to be contacted to fix requested changes. 

Validation check issue for RainbowCrack tool still outstanding, reopened as new issue #1131.

2025-03-06 03:46 UTC, closed without merging