767 feature request sqlmap
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #843
Opened 2024-09-04 08:09 UTC by russo-christian

## Tool Description:
SQLmap is a tool used to detect and exploit SQL injection vulnerabilities in web databases. 

### Tool Features:
The SQLmap tool will run a series of injections against the targeted database. It contains the following configurations:
1. Target URL: the URL or IP of the database to scan
2. Detection Level (1-5): determines how aggressive the scan will be (higher levels will take longer)
3. Risk Level (1-3): determines the types of tests performed, ranging from cautious to aggressive
4. Retrieve Database Banner: if true, will attempt to retrieve the banner of the target database
5. List All Databases: if true, will attempt to to enumerate all databases on the target
6. Retrieve Password Hashes: if true, will attempt to retrieve password hashes from the target database

2024-09-05 05:13 UTC, basoreeper3007 requested changes
Everything else looks good, well done. Just fix those inline comments and I'll approve for merging.

2024-09-06 23:00 UTC, russo-christian commented on src/components/SQLmap/SQLmap.tsx
> +}
changes made

2024-09-06 23:00 UTC, russo-christian commented on src/components/SQLmap/SQLmap.tsx
> +import { Button, Stack, TextInput, Checkbox, Select } from "@mantine/core"; // Added Select
changes made

2024-09-07 03:11 UTC, basoreeper3007 approved these changes
Much better! Good work!

2024-09-07 23:44 UTC, merged