Baselining Enum4Linux
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #844
Opened 2024-09-04 11:25 UTC by rng4302

Baselined Enum4Linux tool

2024-09-04 12:40 UTC, michaeljpigott requested changes
Hi @rng4302 

This is not a full review - it is just a couple of suggestions to help you get past the CI checks. 

Kind regards

Michael

2024-09-11 06:25 UTC, rng4302 commented
Made the changes as suggested. And the check are also passing. Please inform me if any further changes needs to be done

2024-09-12 02:55 UTC, michaeljpigott requested changes
Hi @rng4302 

This is looking pretty good. I did notice that the tool does not appear to be working and I am not sure why:

![image](https://github.com/user-attachments/assets/b107ba75-d55d-43f5-aee1-013abbc6601c)

In the terminal, it looks like this: 

![image](https://github.com/user-attachments/assets/91fe15e0-3cc2-48da-8765-ff5d923ff203)

Do not stress if you cannot fix it because the main purpose of this task is to baseline the tool. 

I have requested some minor changes. 

Kind regards 

Michael

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +import React from "react";
Not required. Can remove. 
```suggestion

```

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +    const [opened, setOpened] = useState(false);
Should only be open if the command is not available.
```suggestion
    const [opened, setOpened] = useState(!isCommandAvailable);
```

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +        "Step 1: Enter the Ip address of the target.\n" +
IP
```suggestion
        "Step 1: Enter the IP address of the target.\n" +
```

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +        "Step 2: Type in the option you want to do enumeration.\n" +
More information required. What options are available? Examples are userlist (-U), machine list (-M), etc.

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +    const sourceLink = ""; // Link to the source code (or Kali Tools).
Enter the link to the Kali page about Enum4Linux.
```suggestion
    const sourceLink = "https://www.kali.org/tools/enum4linux/"; // Link to the source code (or Kali Tools).
```

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +        "Step 3: Enter any additional parameters you want to add.";
Need to add Step 4 about clicking the button. 
```suggestion
        "Step 3: Enter any additional parameters you want to add." + ;
        "Step 4: Click the Start " + title + " button and view the output block to see the results. ";
```

2024-09-12 02:55 UTC, michaeljpigott commented on src/components/Enum4Linux/Enum4Linux.tsx
> +                    <Button type="submit">Scan</Button>
The convention is "Start <title of tool>"
```suggestion
                    <Button type="submit">Start { title }</Button>
```

2024-09-14 00:40 UTC, michaeljpigott commented
@rng4302 Changed the label to "Awaiting Assignee Update" because I am waiting for you to act on the changes requested. 

Kind regards

Michael

2024-09-14 23:59 UTC, michaeljpigott approved these changes
Hi @rng4302 

Thank you for making those changes. I have tested with the parameters that you advised and the tool works. I approve this pull request. 

Kind regards

Michael

2024-09-14 23:59 UTC, merged