variables changed of WPScan to lower case wpscan
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #849
Opened 2024-09-06 16:33 UTC by shreya10-chavan

2024-09-07 03:38 UTC, basoreeper3007 requested changes

2024-09-07 03:38 UTC, basoreeper3007 commented on src-tauri/tauri.conf.json
> +                        "name": "wpscancan",
```suggestion
"name": "wpscan",

2024-09-09 02:40 UTC, michaeljpigott commented
@shreya10-chavan can you please confirm that I can close this pull request because it was replaced by a subsequent one #860?

2024-09-09 12:43 UTC, shreya10-chavan commented
Yes please. You can close it

On Mon, 9 Sept 2024, 12:40 pm michaeljpigott, ***@***.***>
wrote:

> @shreya10-chavan <https://github.com/shreya10-chavan> can you please
> confirm that I can close this pull request because it was replaced by a
> subsequent one #860
> <https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/860>
> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/849#issuecomment-2336999840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEAHFPYN76ZINAYU2ZY6CR3ZVUDDTAVCNFSM6AAAAABNY5GIJKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZWHE4TSOBUGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-09-12 22:46 UTC, michaeljpigott commented
Closing pull request because it was superseded by another one.

2024-09-12 22:46 UTC, closed without merging