Update SMBEnumeration.tsx
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #852
Opened 2024-09-07 03:53 UTC by ZIHRAN1

In this commit, I made several updates to enhance consistency and clarity. I changed the labels in the NativeSelect components from "Scan Speed" to "Scan speed" and from "SMB Script" to "SMB script" to maintain lowercase formatting consistency. I removed redundant references to the UserGuide component and imported and integrated the InstallationModal component, adjusting its usage accordingly. The button text was updated from "Scan" to "Start {title}" to better align with its functionality. Additionally, I improved comments and documentation for clarity, ensuring better maintainability, cleaned up unused variables and imports, and standardized form labels and descriptions for an improved user experience.

2024-09-08 08:51 UTC, basoreeper3007 requested changes
Nice code, only issues are with some indentation, style, and comments. Some inline comments were unnecessary so I have suggested some changes. 

Also please make sure in the future you commit with smaller commits that reflect smaller portions of code changes at a time. Makes it harder to understand the changes you've made when you commit the whole finished code in one go.

After making my suggested changes please run "npx prettier" command on your code for styling the code file. You need to run thisAfter making my suggested changes please run "npx prettier" command on your code for styling the code file. You need to run this so the code can pass the automatic checks.  so the code can pass the automatic checks. If you're not sure how to do that just reach out.

2024-09-08 08:51 UTC, basoreeper3007 commented on src/components/SMBEnumeration/SMBEnumeration.tsx
> +import InstallationModal from "../InstallationModal/InstallationModal"; // Added import
```suggestion
import InstallationModal from "../InstallationModal/InstallationModal";

2024-09-08 08:51 UTC, basoreeper3007 commented on src/components/SMBEnumeration/SMBEnumeration.tsx
> +                                        placeholder={"Select a scan speed. Default set to T3"}
```suggestion
placeholder={"Select a scan speed. Default set to T3"}

2024-09-08 08:51 UTC, basoreeper3007 commented on src/components/SMBEnumeration/SMBEnumeration.tsx
>  const title = "SMB Enumeration"; // Title of the component.
```suggestion
const title = "SMB Enumeration";

2024-09-08 09:19 UTC, basoreeper3007 commented
@ZIHRAN1 instead of making the changes i suggested in code and committing them, you should be able to click "commit suggestion" on my comments.

2024-09-11 07:22 UTC, basoreeper3007 commented
@ZIHRAN1 Still waiting on changes for this before i can approve it.

2024-09-11 07:24 UTC, ZIHRAN1 commented
Hi, i’ve done the changes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bas ***@***.***>
Sent: Wednesday, September 11, 2024 5:22:44 PM
To: Hardhat-Enterprises/Deakin-Detonator-Toolkit ***@***.***>
Cc: MOHAMMED ZIHRAN MOHAMMED SHAFI ***@***.***>; Mention ***@***.***>
Subject: Re: [Hardhat-Enterprises/Deakin-Detonator-Toolkit] Update SMBEnumeration.tsx (PR #852)


@ZIHRAN1<https://github.com/ZIHRAN1> Still waiting on changes for this before i can approve it.

—
Reply to this email directly, view it on GitHub<https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/852#issuecomment-2342858606>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BIHIE2YIIHL6Y7QLS2CXDH3ZV7VUJAVCNFSM6AAAAABNZUXH26VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBSHA2TQNRQGY>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-09-11 07:30 UTC, basoreeper3007 reviewed
It wasn't reflecting your changes properly for me. I refreshed and I can see that all changes have been made.

2024-09-11 07:32 UTC, basoreeper3007 commented
To pass the style check, you need to run prettier on your code.

Running Prettier:
- Navigate to your tsx file in the terminal.
- run the command "npx prettier -w filename.tsx"

2024-09-13 04:20 UTC, basoreeper3007 approved these changes
Good work! I approve.

2024-09-13 06:29 UTC, merged