854 arpspoof missing components
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #887
Opened 2024-09-12 02:49 UTC by vtruglio

As per the attached issue, this request aimed to implement previously missing components into the ARPSpoof tools script, as well as correct misplaced dependencies referencing.

Concerning the pkexec delay issue, this was responded to with recommendations in coinciding documentation for submission.

2024-09-12 08:34 UTC, JacksonGIThuba reviewed
Did manage to get it to work but the process isn't efficient enough to be practical. I changed the number of CPUs on my vm to 5 and it still ran extremely slow becoming quite laggy. It did cause my OS to crash after installing the dependencies.

2024-09-13 00:08 UTC, vtruglio commented
Thanks for the quick reply Jackson.

Unfortunately, the Pkexec issue isn't something that can't be fixed with code implementation at the moment. The inefficiency of the process appears to be a fault with the machine that causes a huge delay in the DDT. As such, I added the required missing components but for the secondary issue of the actual process, I instead made some recommendations as to what could be adopted to fix this issue in the future in my OnTrack submission.

2024-09-15 00:59 UTC, michaeljpigott requested changes
Hi @vtruglio 

Sorry about the misdirection about the dependencies variable. I gave you a bum steer on that one! 

You will need to add the `<stack>` and `LoadingOverlayAndCancelButtonPkexec` components to the UI. See AirbaseNG for the following example:

![image](https://github.com/user-attachments/assets/0d108b4c-823b-4ba3-b71c-08c250e4c006)

Kind regards 

Michael

2024-09-15 00:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +    const dependencies = ["arpspoof"]; // Contains the dependencies required for the component.
Sorry @vtruglio. this is my bad. I was confused about what the dependencies variable should store, but I have subsequently tested it and can confirm that it should be the name of the package that requires installation. Therefore, please change back to dsniff. 
```suggestion
    const dependencies = ["dsniff"]; // Contains the dependencies required for the component.
```

2024-09-15 02:59 UTC, michaeljpigott requested changes
Hi @vtruglio 

This is very close. You just accidentally added the loading overlay twice. Can you please remove the 2nd one? 

Kind regards

Michael

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                        {LoadingOverlayAndCancelButtonPkexec(
You have included the loading overlay twice. Need to remove the 2nd one. 
```suggestion
                    
```

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                            loading,
```suggestion
                         
```

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                            pidTarget,
```suggestion
                         
```

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                            handleProcessData,
```suggestion
                          
```

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                            handleProcessTermination
```suggestion
                          
```

2024-09-15 02:59 UTC, michaeljpigott commented on src/components/ArpSpoof/ArpSpoof.tsx
> +                        )}
```suggestion
                      
```

2024-09-15 03:22 UTC, vtruglio commented
Thanks Michael.

I've added two loading overlays as the tool utilises both a pidGateway and pidTarget variables. When testing with these both overlays, the tool did perform arpspoofing and return an output.

2024-09-15 03:35 UTC, michaeljpigott commented
Hi @vtruglio, 

Good point - I forgot about that! 

Michael

2024-09-15 03:36 UTC, michaeljpigott approved these changes
Hi @vtruglio 

Thank you for making those changes. The tool looks a lot better now. 

Kind regards

Michael

2024-09-15 03:36 UTC, merged