Fix dnsenum components
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #894
Opened 2024-09-13 13:34 UTC by junedtk632

The missing components were added with several key fixes and improvement to DNSenumTool, addressing errors and enhancing functionality related to command availability, process management and component initialization using useEffect. 
1. **checkAllCommandsAvailability** component added, which verifies if necessary commands dnsenum, kill are installed on the system or not. 
2. Displays an **InstallationModal** component if commands are missing, guiding use to install them manually. 
3. The **useEffect** component triggers command availability check when the component is mounted. It ensures that command validation happens automatically upon loading the tool, without requiring user interaction. 
4. Process termination issues are also fixed. Provided feedback for different termination scenarios such as successful completion, manual termination, or errors. 

![image](https://github.com/user-attachments/assets/3a6da235-6d82-4abc-9c88-522a1d9b98da)

2024-09-15 01:39 UTC, michaeljpigott commented
@junedtk632 

You need to fix the conflict with DNSenumTool.tsx. I think you based this branch on an outdated version of because the tool has already been baselined. 

Kind regards

Michael

2024-09-15 23:25 UTC, michaeljpigott commented
@junedtk632 you need to run `yarn run style` and `npx prettier --write <file path>` to fix the failed CI check.

2024-09-18 23:58 UTC, michaeljpigott commented
@junedtk632 is this ready for review again?

2024-09-19 00:05 UTC, junedtk632 commented
Yes, it is ready to review again. I have checked there are no errors in the
build on github.

On Thu, 19 Sep 2024 at 9:58 am, michaeljpigott ***@***.***>
wrote:

> @junedtk632 <https://github.com/junedtk632> is this ready for review
> again?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/894#issuecomment-2359645013>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX3H7P4AJ4O5CZ64QBZCAX3ZXIHT3AVCNFSM6AAAAABOFMTUWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJZGY2DKMBRGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2024-09-19 04:24 UTC, michaeljpigott requested changes
Hi @junedtk632 

Nice attempt but I think you may have made this a bit more difficult than it needs to be. DDT has already got components for checking command availability and the installation model, so I recommend you use those. 

Kind regards

Michael

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +    const checkAllCommandsAvailability = async () => {
Interesting way of implementing this. I am getting the following: 

![image](https://github.com/user-attachments/assets/a4e40ae9-4611-4a83-9fa4-1d5a1217f1a0)

I recommend implementing as per our other tools.

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +    const checkAllCommandsAvailability = async () => {
```suggestion
    // Check the availability of commands in the dependencies array
    useEffect(() => {
        checkAllCommandsAvailability(dependencies)
            .then((isAvailable) => {
                setIsCommandAvailable(isAvailable);
                setOpened(!isAvailable);
                setLoadingModal(false);
            })
            .catch((error) => {
                console.error("An error occurred:", error);
                setLoadingModal(false);
            });
    }, []);
```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +
I recommend replacing these lines with our conventional use of useEffect()
```suggestion
      

```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +import { Button, LoadingOverlay, Stack, TextInput, Switch, Modal } from "@mantine/core";
You also need to import checkAllCommandsAvailability and Installation Modal. 
```suggestion
import { Button, LoadingOverlay, Stack, TextInput, Switch, Modal } from "@mantine/core";
import { checkAllCommandsAvailability } from "../../utils/CommandAvailability";'
import InstallationModal from "../InstallationModal/InstallationModal";

```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +                    <Modal opened={modalOpened} onClose={() => setModalOpened(false)} title="Missing Commands">
Interesting implementation but I recommend that you add the conventional component installationModal. Here is an example of what it looks like in WhatWeb: 

![image](https://github.com/user-attachments/assets/3f7c0372-d261-459f-b4d6-1680fe62579a)
```suggestion
                 
```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +                    </Modal>
Remove once you add the convention installationModal component. 
```suggestion
                   
```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +    const dependencies = ["dnsenum", "kill"]; // Dependencies required by the component
Should not require kill
```suggestion
    const dependencies = ["dnsenum"]; // Dependencies required by the component
```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +    const [missingCommands, setMissingCommands] = useState<string[]>([]);
The checkAllCommandsAvailability and installationModal components require some specific variables. 
```suggestion
    const [isCommandAvailable, setIsCommandAvailable] = useState(false); // State variable to check if the command is available.
    const [opened, setOpened] = useState(!isCommandAvailable); // State variable that indicates if the modal is opened.
    const [loadingModal, setLoadingModal] = useState(true); // State variable to indicate loading state of the modal.
    
    
```

2024-09-19 04:24 UTC, michaeljpigott commented on src/components/DNSenumTool/DNSenumTool.tsx
> +    const [modalOpened, setModalOpened] = useState(false);
This will not be required once you use the pre-made component. 
```suggestion
  
```

2024-09-20 06:08 UTC, michaeljpigott approved these changes
Hi @junedtk632 

Thank you for making those changes. The tool looks good and I approve the pull request. 

Kind regards

Michael

2024-09-20 06:08 UTC, merged