made changes as told
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #897
Opened 2024-09-13 14:41 UTC by shivang2311

In the SearchSploit task, I focused on fixing a baseline bug by updating the component according to a predefined checklist. This included standardizing the code, removing unnecessary imports, and ensuring proper use of React hooks and components like LoadingOverlayAndCancelButtonPkexec. I also followed the project's style guide to ensure consistency.

2024-09-14 02:10 UTC, Cyriacjose requested changes
Hi @shivang2311 
The code still needs some work.

Please use Rendercomponent and dependencies to return.
Could you please kindly refer to AirbaseNG, or AircrackNG codes.

Regards

2024-09-14 09:23 UTC, Cyriacjose requested changes
Hi @shivang2311,

We are almost there just two changes required
Need Conditional Rendering ({!loadingModal && ...}): refer to Aircrack or Airbase code.
![image](https://github.com/user-attachments/assets/2c36c10d-b34d-4f34-b75a-cf118c790024)

If you're not using the Switch component, you can remove its import statement from the first line.

2024-09-14 12:51 UTC, shivang2311 commented
made changes as told @Cyriacjose                                                                                                                                                                       Thanks!!

2024-09-15 11:26 UTC, Cyriacjose requested changes
Render Component not called

2024-09-15 14:32 UTC, Oliver2049 commented on src/components/SearchSploit/SearchSploit.tsx
> +const sourceLink = "https://www.exploit-db.com/documentation/Offsec-SearchSploit.pdf";
I think you used the wrong link for sourceLink, it should be like this:
```suggestion
const sourceLink = "https://www.kali.org/tools/exploitdb/#searchsploit";
```

2024-09-15 14:58 UTC, Oliver2049 commented on src/components/SearchSploit/SearchSploit.tsx
You forgot  to call import { RenderComponent } from "../UserGuide/UserGuide";
```suggestion
import { RenderComponent } from "../UserGuide/UserGuide";
```

2024-09-15 14:59 UTC, Oliver2049 commented on src/components/SearchSploit/SearchSploit.tsx
> +        <>
You for got to use RederComponent here
```suggestion
         <RenderComponent
            title={title}
            description={description}
            steps={steps}
            tutorial={tutorial}
            sourceLink={sourceLink}
        >
```

2024-09-15 15:00 UTC, Oliver2049 commented on src/components/SearchSploit/SearchSploit.tsx
> +        </>
Close RenderComponent here
```suggestion
        </RenderComponent>
```

2024-09-15 15:03 UTC, Oliver2049 commented on src/components/SearchSploit/SearchSploit.tsx
> +                    <Button type={"submit"}>Scan</Button>
You should use Start {title}
```suggestion
                    <Button type={"submit"}>Start {title}</Button>
```

2024-09-16 12:23 UTC, Oliver2049 approved these changes
Hi @shivang2311 
OVerall, this looks good to me. Thanks for your effort.
Regards, 
Oliver

2024-09-16 12:25 UTC, Cyriacjose approved these changes
Look good Tested on local environment seems working fine.
Great work @shivang2311

2024-09-16 12:25 UTC, merged