first 1388
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #916
Opened 2024-09-15 08:33 UTC by Shreeyut

Added python file for exploit and typescript for UI
The exploit requires an X-05 authentication token to work. Currently this is only possible with third party tools.

2024-09-16 08:13 UTC, BrennanHarrell requested changes
Hi @Shreeyut,

Overall, the implementation looks good. However, there are some changes needed to ensure the tool functions as expected. I’ve also included a few suggestions to improve consistency and correctness.

2024-09-19 06:07 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +arser.add_option('-a', '--auth', action="store", dest="url", help="X-F5-Authorization token")
Changed dest to host and auth

2024-09-19 06:07 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +    exit()
added validation checks

2024-09-19 06:07 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'Host': url_vuln,
yup changed it to host_vuln

2024-09-19 06:08 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'X-F5-Auth-Token': 'asdf',
Changed headers

2024-09-19 06:12 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +arser.add_option('-a', '--auth', action="store", dest="url", help="X-F5-Authorization token")
fixed typo

2024-09-19 06:13 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'X-F5-Auth-Token': 'asdf',
changed headers

2024-09-19 06:13 UTC, Shreeyut commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +                    <TextInput label={"Target IP"} required {...form.getInputProps("targetIp")} />
fixed typos for variables

2024-09-19 06:13 UTC, Shreeyut commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +// Descripption used to inform the user about the exploit
fixed typo

2024-09-19 06:13 UTC, Shreeyut commented on src/components/RouteWrapper.tsx
> +        description: "undisclosed requests may bypass iControl REST authentication.",
capitalized for consistency

2024-09-19 06:14 UTC, Shreeyut commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +            values.authtoken,
changed to proper token flag

2024-09-19 06:14 UTC, Shreeyut commented
All requested changes implemented

2024-09-20 12:27 UTC, BrennanHarrell requested changes
Hey @Shreeyut,

I’ve made a few more minor suggestions. Additionally, I noticed that there’s currently no way to test the tool in DDT, as there isn’t a button to run it after entering all the parameters.

Could you please look into this issue?

Kind Regards,
Brennan

<img width="784" alt="auth" src="https://github.com/user-attachments/assets/0803160a-0a6d-49da-b05b-c4bb4e8e5285">

2024-09-20 16:17 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'X-F5-Auth-Token': 'auth_vuln',
removed quotations

2024-09-20 16:17 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'X-F5-Auth-Token': options.auth,
changed auth variable

2024-09-20 16:18 UTC, Shreeyut commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +    "versions undisclosed requests may bypass iControl REST authentication.\n";
fixed formatting

2024-09-20 16:18 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +        'X-F5-Auth-Token': 'auth_vuln',
removed quotations

2024-09-20 16:20 UTC, Shreeyut commented
i added the exploit button i missed. I did see a couple implementations of the poc working as intended but obtaining the authentication token for testing seemed quite challenging.

2024-09-21 04:46 UTC, BrennanHarrell requested changes
Hey @Shreeyut,

As you noted, legitimately testing this tool in quite difficult, I would need to get a F5 BIG-IP VM to honestly do so. I’ve conducted some basic tests to identify any issues and have a few minor suggestions to improve functionality.

Additionally, similar to the issue raised in #919, I encountered a problem while testing the implementation in DDT. The tool continues to load indefinitely, and pressing the "cancel" button does not have any effect, forcing me to close the DDT tool to stop it. In contrast, the standalone script exits as expected.

Could you please investigate this issue?

Thanks.

2024-09-21 04:46 UTC, BrennanHarrell commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +            "-h",
Need to change the option from -h to something like -H.

```suggestion
            "-H",
```

2024-09-21 04:46 UTC, BrennanHarrell commented on src-tauri/exploits/CVE-2022-1388.py
> +ps1 = []
The url_vuln variable lacks URL schemes (http:// or https://), which causes an error when trying to run it. Please update the url_vuln variable to ensure it starts with a valid protocol, such as https://

```suggestion
auth_vuln = options.auth

# Ensure the URL has a valid schema
if not url_vuln.startswith('http://') and not url_vuln.startswith('https://'):
    url_vuln = 'https://' + url_vuln  # Assuming HTTPS, change to HTTP if needed

cmd_1 = []
ps1 = []
```

2024-09-21 10:10 UTC, BrennanHarrell commented on src-tauri/exploits/CVE-2022-1388.py
> +    `
Please remove the stray single quotation mark here.
```suggestion
    
```

2024-09-21 10:12 UTC, BrennanHarrell requested changes

2024-09-21 10:12 UTC, BrennanHarrell commented on src-tauri/exploits/CVE-2022-1388.py
> +    `
Please remove the stray single quotation mark here.
```suggestion
    
```

2024-09-21 10:44 UTC, BrennanHarrell requested changes
Hi @Shreeyut,

Almost there. Other than this change, just be sure to run a style check to ensure everything is formatted properly.

Thanks.

2024-09-21 10:44 UTC, BrennanHarrell commented on src-tauri/exploits/CVE-2022-1388.py
> +    `
Please remove the stray single quotation mark here.
```suggestion
    
```

2024-09-21 23:37 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +parser.add_option('-h', '--host', action="store", dest="host", help="Host IP address")
changed parameter

2024-09-21 23:37 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +ps1 = []
updated url_vuln

2024-09-21 23:37 UTC, Shreeyut commented on src/components/CVE-2022-1388/CVE-2022-1388.tsx
> +            "-h",
changed paramter

2024-09-21 23:38 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-1388.py
> +    `
Yup ive fixed the formatting and removed the quotation mark. I had internet issues and was unable to push the style fix yesterday sorry.

2024-09-22 00:53 UTC, BrennanHarrell approved these changes
Hey @Shreeyut,

Thanks for making those changes and adding the error handling to address the mentioned issue. Everything looks good to me; I’ve tested the app, and while it is, of course, a difficult one to properly test, I’m not encountering any unexpected errors. The functionality and output align with the expected behaviour when not used against an F5 BIG-IP, so I approve this pull request.

Kind regards,
Brennan

2024-09-22 07:37 UTC, merged