27925 python and typescript
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #919
Opened 2024-09-15 10:40 UTC by Shreeyut

Added python exploit and typescript for 2022-27925

2024-09-17 08:14 UTC, BrennanHarrell requested changes
Hey @Shreeyut,

Code looks good; I have made a few minor suggestions. On another note, testing this tool can be challenging due to its requirements. For simplicity, I tested it on a non-existent site to observe its behaviour. I used both the exploit script and the DDT tool. However, when testing the implementation in DDT, the tool continues to load indefinitely, and pressing the "cancel" button has no effect, requiring me to close the DDT tool to stop it. In contrast, the standalone script exits as expected.

Could you please look into this issue?

<img width="745" alt="loading" src="https://github.com/user-attachments/assets/540396ae-caa6-48ec-8ac8-c48fcc5ade29">

2024-09-18 19:38 UTC, Shreeyut commented on src-tauri/exploits/CVE-2022-27925.py
> +webshell_payload = r'<%@ page import="java.util.*,java.io.*"%><%%><HTML><BODY><FORM METHOD="GET" NAME="myform" ACTION=""><INPUT TYPE="text" NAME="cmd"><INPUTTYPE="submit" VALUE="Send"></FORM><pre><%i
I added this correction

2024-09-18 19:38 UTC, Shreeyut commented on src/components/CVE-2022-27925/CVE-2022-27925.tsx
> +// Descripption used to inform the user about the exploit
fixed this typo

2024-09-18 19:39 UTC, Shreeyut commented on src/components/CVE-2022-27925/CVE-2022-27925.tsx
> +    "vinux kernel and could thus contain stale values. An unprivileged local user could use this flaw to write to pages in the page cache backed by read only files and as such escalate their privileg
sorry was working on multiple cves. fixed this issue

2024-09-18 19:39 UTC, Shreeyut commented on src/components/CVE-2022-27925/CVE-2022-27925.tsx
> +                    <TextInput label={"URl with protocol HTTPS"} required {...form.getInputProps("targetIp")} />
fixed this typo too

2024-09-18 19:39 UTC, Shreeyut commented on src/components/CVE-2022-27925/CVE-2022-27925.tsx
> +     * @param {string} data - The string data recieved from the child process.
fixed this typo as well

2024-09-18 19:42 UTC, Shreeyut commented
> Hey @Shreeyut,
> 
> Code looks good; I have made a few minor suggestions. On another note, testing this tool can be challenging due to its requirements. For simplicity, I tested it on a non-existent site to observe its behaviour. I used both the exploit script and the DDT tool. However, when testing the implementation in DDT, the tool continues to load indefinitely, and pressing the "cancel" button has no effect, requiring me to close the DDT tool to stop it. In contrast, the standalone script exits as expected.
> 
> Could you please look into this issue?
> <img alt="loading" width="745" src="https://private-user-images.githubusercontent.com/141468548/368075988-540396ae-caa6-48ec-8ac8-c48fcc5ade29.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODQ4OTYsIm5iZiI6MTcyNjY4NDU5NiwicGF0aCI6Ii8xNDE0Njg1NDgvMzY4MDc1OTg4LTU0MDM5NmFlLWNhYTYtNDhlYy04YWM4LWM0OGZjYzVhZGUyOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxODM2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZTIxZWM1OWM5NzMwOWVhODhlM2E4MzUxMmUxYmM4YzFjYTlmZGE5NmUwZmRiODRhZjhmMzRjOTM4OWM2NGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P5uRZLCxo-QvwyAbKj6ybhGR7E7Gv3dI3kTSdusn9QE">

I looked into this issue and added the error handling to mitigate it. It should work as intended now.
![image](https://github.com/user-attachments/assets/68085bc2-941c-47c9-9c25-4bdf547703d3)

2024-09-18 19:56 UTC, Shreeyut commented
All requests resolved awaiting approval.

2024-09-19 03:31 UTC, BrennanHarrell approved these changes
Hey @Shreeyut,

Thanks for making those changes and adding the error handling to address the mentioned issue. Everything looks good to me; I’ve tested the app, and it works flawlessly now, so I approve this pull request.

Kind regards,
Brennan

2024-09-19 03:49 UTC, merged