Firmware Analysis toolkit
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #921
Opened 2024-09-15 18:18 UTC by Tillu6

FAT (Firmware Analysis Toolkit) is a powerful tool designed to analyze and reverse engineer firmware images. It provides a comprehensive set of features for tasks such as:

Disassembly: Disassembles firmware into human-readable assembly code.
Decompilation: Attempts to convert assembly code into a higher-level programming language (e.g., C).
Static analysis: Identifies potential vulnerabilities, security flaws, and other characteristics of the firmware.
Dynamic analysis: Executes the firmware in a simulated environment to observe its behavior and interactions.
Debugging: Provides tools for debugging and troubleshooting firmware issues.
FAT is often used by security researchers, reverse engineers, and software developers to understand the inner workings of firmware, identify vulnerabilities, and develop security patches or new firmware versions.

2024-09-16 00:16 UTC, michaeljpigott requested changes
Hi @Tillu6 

Can you please confirm if firmadyne is the correct dependency because when trying to install it on my machine, I cannot find it: 

![image](https://github.com/user-attachments/assets/eb392ff8-ca21-423c-a356-e631c040faba)

Can you also provide an example firmware image file, or steps on how to obtain one? We will need it for testing. 

Kind regards

Michael

2024-09-16 00:16 UTC, michaeljpigott commented on src/pages/Tools.tsx
> +        "IOT",
Please sort alphabetically.

2024-09-16 00:16 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> -import TestSSL from "./Testssl/Testssl";
I do not think you need to delete this.

2024-09-16 00:16 UTC, michaeljpigott commented on src/components/RouteWrapper.tsx
> +        name: "FirmwareAnalysisTool",
This is sorted alphabetically. Can you please place after FFuf?

2025-03-06 05:45 UTC, GoldenBanksia commented
PR requested changes, including giving an example for testing not completed. Dependency installation not working properly, nor able to get tool working on branch version of DDT or CLI. 

Possible that this tool is no longer maintained by Attify: https://github.com/attify/firmware-analysis-toolkit there is also a known outstanding issue on the src repo with running this on Kali linux, which does not look like it is being updated/maintained.

PR closed + branch deleted. Tool addition to the toolkit not reopened due to outdated and unmaintained source package.

2025-03-06 05:45 UTC, closed without merging