Implementation for TShark Analyzer feature.
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #927
Opened 2024-09-16 04:32 UTC by s223915833

Three options implemented in analyzer feature. 1. Protocol statistics, 1. TCP conversations, 3. HTTP Requests.

2024-09-17 00:10 UTC, michaeljpigott requested changes
Hi @s223915833 

This looks like a good change that extends the functionality of tshark. 

I would like you to change the spelling of Analyzer to Analyser to match with Australian spelling conventions. 

Also please remove the console.logs because they are not required once a tool goes into production. 

Kind regards

Michael

2024-09-17 00:10 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        "Step 11: Provide the file path for the capture file.\n" +
What should the file extension for the capture file be?

2024-09-17 00:10 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        "Step 12: Seletc the Analyzer type and click start TShark";
Typo in select. Change analyser to analysis to match field. 
```suggestion
        "Step 12: Select the analysis type and click start TShark";
```

2024-09-17 00:10 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        console.log("Form submitted with values: ", values);
Remove console.log. Not required. 
```suggestion
       
```

2024-09-17 00:10 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +                console.log("Analyzer ", analysisCommand);
Remove console.log. Not required. 
```suggestion
            
```

2024-09-20 08:30 UTC, s223915833 commented
Thanks for the review @michaeljpigott Corrected the Spellings and removed console logs.

2024-09-20 23:32 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        "TShark is a tool used to capture network traffic and write it to a capture file. The captured traffic can be viewed directly by opening the file, otherwise the Reader option can be used to o
Hi @s223915833, you missed this change.

2024-09-20 23:32 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        "Step 12: Seletc the Analyzer type and click start TShark";
Hi @s223915833, you missed this change.

2024-09-20 23:40 UTC, michaeljpigott requested changes
Hi @s223915833 

Thank you for making those changes. I noticed that there are a couple of recommended changes that you missed, namely: 

- Changing Analyzer to Australian spelling and lowercase a in the description variable;
- Adding examples of what file extension are allowed for Step 11. 

I also recommend deleting the console.log in the onSubmit variable rather than commenting it out. 

Kind regards

Michael

2024-09-20 23:40 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        //console.log("Form submitted with values: ", values);
I recommend deleting this line rather than commenting it out.

2024-09-20 23:40 UTC, michaeljpigott commented on src/components/TShark/TShark.tsx
> +        "Step 11: Provide the file path for the capture file.\n" +
I still recommend adding an example file extension, e.g. pcap, etc.

2025-03-16 12:32 UTC, GoldenBanksia commented
Closing PR as TShark to be removed from toolkit as approved in ADR 0009.

2025-03-16 12:32 UTC, closed without merging