875 feature request exif tool
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #928
Opened 2024-09-16 05:27 UTC by SUA-321

Completed Exif Tool and tested thoroughly, added code standardisation.

2024-09-16 05:37 UTC, basoreeper3007 commented
I will review later today. :)

2024-09-16 07:08 UTC, basoreeper3007 submitted a review, later dismissed
Great work here @SUA-321! Please make the requested changes and I will approve it for merging. I tested the application and I'm happy with its functionality.

2024-09-16 07:11 UTC, basoreeper3007 commented on src/components/RouteWrapper.tsx
> +    },
Routewrapper tools should be in alphabetical order. Please place Exif above EyeWitness.

2024-09-16 07:16 UTC, basoreeper3007 commented on src/components/Exif/Exif.tsx
> +        "Step 5: Run the tool!"; // Steps explaining how to run tool
Simplification of user guide. Also some fixes with punctuation and formatting.

```suggestion
        "Step 1: Specify the file path of an image on your machine.\n" +
        "Step 2: Enter a metadata tag to read or write to.\n" +
        "Step 3: Choose whether to read or write to the specified metadata field.\n" +
        "Step 4: Input a value to write to the specified metadata field.\n" +
        "Step 5: Run the tool!";

2024-09-16 07:17 UTC, basoreeper3007 requested changes
Great work, now please make the changes I have suggested above. As mentioned earlier I have conducted application testing on this tool.

2024-09-16 13:08 UTC, basoreeper3007 approved these changes
Great job @SUA-321! I have tested this tool and I approve it for merging @michaeljpigott.

2024-09-16 23:52 UTC, michaeljpigott requested changes
Hi @SUA-321 

Can you please explain why you need to use pkexec for this tool? 

It appears to run in the terminal without sudo: 

![image](https://github.com/user-attachments/assets/08a4dde5-6812-4578-869c-f1e86052f00b)

It also appears that the loading overlay is not working when I use the tool. 

I would have thought that you need to add exiftool as a scoped command in tauri.conf.json. 

Kind regards

Michael

Kind regards 

Michael

2024-09-27 02:47 UTC, michaeljpigott approved these changes
Hi @SUA-321 

I approve this pull request although when testing, the loading overlay still did not appear. No worries, good work and it looks like a good tool. 

Kind regards

Michael

2024-09-27 02:47 UTC, merged