Updated WPScan.tsx with new UI and parameters
Hardhat-Enterprises/Deakin-Detonator-Toolkit pull request #941
Opened 2024-09-16 13:44 UTC by chandelshubham63

Improve the **WPScan tool interface.** Maintain existing functionality while adding some more crucial specific parameters (e.g., random user agent, force SSL, proxy settings). Reorganize options into collapsible sections and implement a three-step process using the Stepper component. This enhancement aims to improve usability for users and maintain a consistent look in the toolkit.

2024-09-16 13:49 UTC, chandelshubham63 commented
@michaeljpigott  I have thoroughly tested the tool and checked the format, so you shouldn’t encounter any issues. It is ready to be merged into the main branch :)

2024-09-17 05:56 UTC, michaeljpigott requested changes
Hi @chandelshubham63 

Looks good. Just a couple of small suggestions. I did not test the tool because I do not have a WordPress website running ATM. 

Kind regards

Michael

2024-09-17 05:56 UTC, michaeljpigott commented on src/components/WPScan/WPScan.tsx
> +        "Step 3: Click Scan to commence WPScan's operation.\n" +
The convention is Start + title of tool. 
```suggestion
        "Step 3: Click Start " + title + " to commence WPScan's operation.\n" +
```

2024-09-17 05:56 UTC, michaeljpigott commented on src/components/WPScan/WPScan.tsx
> +                                        Run WPScan
The convention is Start + title of tool. 
```suggestion
                                        Start {title}
```

2024-09-20 05:56 UTC, chandelshubham63 commented
@michaeljpigott  all requested changes completed, ready to merge thanks:)

2024-09-20 06:11 UTC, michaeljpigott approved these changes
Hi @chandelshubham63 

Thank you for making those changes. I approved this pull request. 

Kind regards

Michael

2024-09-20 06:12 UTC, merged